import { useI18n } from './i18n/I18nProvider';
export default function Landing({ onNavigate, onSettings }: { onSettings: () => void; onNavigate: (page: 'learn' | 'lab' | 'technology') => void }) {
  const { locale } = useI18n(), t = (ko: string, en: string) => locale === 'ko' ? ko : en;
  const entries = [
    { id: 'learn', icon: '01', title: t('백엔드 학습', 'Backend Learning'), description: t('Java, Python, JavaScript/TypeScript, C# 중 하나를 골라 시작하세요. 언어와 환경 준비부터 API·DB·테스트·운영까지, 작은 예제로 차근차근 배웁니다.', 'Choose Java, Python, JavaScript/TypeScript or C#. Learn from language and environment basics to APIs, databases, testing and operations through small examples.'), button: t('학습 언어 선택하기', 'Choose a learning language') },
    { id: 'lab', icon: '02', title: t('자유실험실', 'Free lab'), description: t('로컬에서 실행 중인 실제 서비스에 세션별 장애를 설정하고 관찰하는 공간입니다. 지표와 로그를 수집하고 근거로 원인을 분석한 뒤 장애를 해제해 회복을 확인합니다.', 'Set and observe session-scoped faults in real services running locally. Collect metrics and logs, diagnose from evidence, then disable the fault and check recovery.'), button: t('자유실험실 열기', 'Open the free lab') },
    { id: 'technology', icon: '03', title: t('기술 사전', 'Technology guides'), description: t('HTTP, DB, 캐시, 메시징과 관측 도구가 어떤 문제를 해결하는지 살펴보세요. 공통 개념을 읽고 선택한 언어의 관련 수업으로 돌아갈 수 있습니다.', 'Explore what HTTP, databases, caching, messaging and observability tools solve. Read shared concepts and return to a related lesson in your chosen language.'), button: t('기술 사전 둘러보기', 'Explore technology guides') },
  ] as const;
  return <section className="unified-landing"><header className="landing-intro"><span className="learning-kicker">INCIDENTLENS · {t('로컬 백엔드 학습 공간', 'Your local backend learning space')}</span><h1>{t('이해하고, 만들어 보고,', 'Understand. Build.')}<br />{t('근거로 확인하세요.', 'Verify with evidence.')}</h1><p>{t('처음 배우는 개념부터 실제 서비스의 장애 분석까지.\n지금 필요한 곳에서 시작하세요.', 'From your first concepts to fault analysis in real services.\nStart where you need to be.')}</p></header><div className="landing-cards">{entries.map(entry => <article className="landing-card" key={entry.id}><span className="intro-number">{entry.icon}</span><h2>{entry.title}</h2><p>{entry.description}</p><button className={entry.id === 'learn' ? 'learn-primary' : 'learn-secondary'} onClick={() => onNavigate(entry.id)}>{entry.button}<span aria-hidden="true"> →</span></button></article>)}</div><div className="landing-note"><span aria-hidden="true">◌</span><p>{t('학습은 서비스 없이도 읽을 수 있습니다. 자유실험실은 Java / Spring Boot 기반 로컬 서비스이며, 다른 언어의 연습 프로젝트와 구분됩니다. 이동만으로 실험이 실행되지는 않습니다.', 'Read lessons without running services. The free lab runs local Java / Spring Boot services, distinct from the other languages’ practice projects. Navigation never starts an experiment.')}</p></div><button className="text-button landing-setup-link" onClick={onSettings}>{t("내 PC의 실행 준비와 포트 설정 안내", "Prepare your PC and plan local ports")} →</button></section>;
}
