import { useI18n } from './i18n/I18nProvider';
export default function Landing({ onNavigate, onSettings }: { onSettings: () => void; onNavigate: (page: 'lab' | 'evidence' | 'comparison' | 'technology') => void }) {
  const { locale } = useI18n(), t=(ko:string,en:string)=>locale==='ko'?ko:en;
  const entries=[
    {id:'lab',icon:'01',title:t('장애 재현과 부하','Faults and load'),description:t('자체 Java / Spring 데모에 세션별 장애를 적용합니다. 터미널의 k6로 정해진 요청 부하를 실행하고 지연·오류·캐시·대기열 변화를 관찰하세요.','Apply session-scoped faults to our Java / Spring demo. Run a defined k6 workload in a terminal and observe latency, errors, cache behavior and backlogs.'),button:t('자유실험실 열기','Open the free lab')},
    {id:'evidence',icon:'02',title:t('근거와 원인 분석','Evidence and RCA'),description:t('관측 지표와 사건을 세션의 근거로 수집합니다. 무료 규칙 기반 RCA에서 관찰·가설·불확실성을 구분하고 저장된 보고서를 다시 확인하세요.','Collect observed metrics and events as session evidence. Read observations, hypotheses and uncertainties in free rule-based RCA, then revisit the saved report.'),button:t('근거와 RCA 확인','Open evidence and RCA')},
    {id:'comparison',icon:'03',title:t('복구와 전후 비교','Recovery and comparison'),description:t('장애 적용 구간과 해제 후 구간에 같은 부하를 실행합니다. 실행 구성·부하·측정 시간과 함께 변화를 확인하며, 다른 PC를 동일 조건으로 간주하지 않습니다.','Run the same workload during the fault and after recovery. Compare changes alongside configuration, workload and measurement windows; different PCs are not equivalent conditions.'),button:t('전후 비교 열기','Open before / after comparison')},
  ] as const;
  return <section className="unified-landing"><header className="landing-intro"><span className="learning-kicker">INCIDENTLENS · {t('로컬 장애·부하 테스트 도구','Local fault and load testing')}</span><h1>{t('장애를 재현하고,','Reproduce faults.')}<br/>{t('근거로 변화를 확인하세요.','Inspect the evidence.')}</h1><p>{t('실행 → 측정 → 복구 → 보고서 확인.\n자체 데모 서비스에서 실험하고, 관찰과 추정을 구분합니다.','Run → measure → recover → inspect the report.\nExperiment with our demo services and separate observations from hypotheses.')}</p></header><div className="landing-cards">{entries.map(entry=><article className="landing-card" key={entry.id}><span className="intro-number">{entry.icon}</span><h2>{entry.title}</h2><p>{entry.description}</p><button className={entry.id==='lab'?'learn-primary':'learn-secondary'} onClick={()=>onNavigate(entry.id)}>{entry.button}<span aria-hidden="true"> →</span></button></article>)}</div><div className="landing-note"><span aria-hidden="true">◌</span><p>{t('현재 대상은 IncidentLens 자체 데모 서비스입니다. 임의의 사용자 프로젝트 연동과 원격 장애 실험은 구현되지 않았습니다. 화면 이동만으로 장애·부하·보고서 생성이 실행되지는 않습니다.','Targets are IncidentLens’s own demo services. Arbitrary user-project integration and remote fault experiments are not implemented. Navigation never sets faults, runs load or generates reports.')}</p></div><button className="text-button landing-setup-link" onClick={()=>onNavigate('technology')}>{t('실험 이해를 위한 기술 사전','Technology guides for interpreting experiments')} →</button><button className="text-button landing-setup-link" onClick={onSettings}>{t('내 PC의 실행 준비와 포트 설정 안내','Prepare your PC and plan local ports')} →</button></section>;
}
