import { useEffect, useState } from 'react';
import { useI18n } from './i18n/I18nProvider';
import { readPlatform, savePlatform, type LearningPlatform } from './execution-platform';
const key = 'incidentlens.pc-settings.draft.v1';
const defaults = { mode: 'core', ports: { CONTROL_PLANE_PORT: 8080, DEMO_API_PORT: 8081, DEMO_WORKER_PORT: 8082, WEB_PORT: 3000, PROMETHEUS_PORT: 9090, GRAFANA_PORT: 3001 }, vus: 2, duration: 10 };
type Draft = typeof defaults;
function readDraft(): Draft {
  try {
    const d = JSON.parse(localStorage.getItem(key) ?? 'null');
    if (!d) return defaults;
    return { mode: ['frontend','core','observability'].includes(d.mode) ? d.mode : d.mode === 'learning' ? 'frontend' : 'core', ports: Object.fromEntries(Object.entries(defaults.ports).map(([k,v]) => [k, Number.isInteger(d.ports?.[k]) && d.ports[k] >= 1 && d.ports[k] <= 65535 ? d.ports[k] : v])) as Draft['ports'], vus: Number.isInteger(d.vus) && d.vus >= 1 && d.vus <= 50 ? d.vus : 2, duration: Number.isInteger(d.duration) && d.duration >= 5 && d.duration <= 300 ? d.duration : 10 };
  } catch { return defaults; }
}
export default function PcSettings() {
  const { locale } = useI18n(), t = (ko: string,en: string) => locale === 'ko' ? ko : en;
  const [draft,setDraft] = useState(readDraft);
  const [platform,setPlatform] = useState<LearningPlatform>(() => { try { return readPlatform(localStorage); } catch { return 'linux'; } });
  const [stored,setStored] = useState(true);
  const [runtime,setRuntime] = useState<{profile:string;hostPorts:Record<string,number>} | null>(null);
  const [checked,setChecked] = useState(false);
  useEffect(() => { const abort = new AbortController();fetch('/api/runtime',{signal:abort.signal}).then(r => { if (!r.ok) throw Error();return r.json(); }).then(d => {if(typeof d?.profile!=="string" || typeof d?.hostPorts?.web!=="number")throw Error("Invalid runtime configuration response");setRuntime(d);setChecked(true);}).catch(() => {if (!abort.signal.aborted)setChecked(true);});return () => abort.abort(); },[]);
  function update(next: Draft) { setDraft(next);try { localStorage.setItem(key,JSON.stringify(next));setStored(true); }catch {setStored(false);} }
  const win = platform === 'windows';
  const modes = [
    { id:'frontend',title:t('화면만','UI only'),services:t('로컬 Node.js와 웹 개발 서버','Local Node.js and the web development server'),text:t('실험 화면과 관련 기술 설명만 살펴봅니다. 일반 백엔드 학습은 별도 비공개 프로젝트입니다. Docker가 필요 없으며 API 연결·장애·부하·근거·RCA·비교는 사용할 수 없습니다.','View the experiment interface and related technology explanations. General learning moved to a separate private project. No Docker is needed; API connections, faults, load, evidence, RCA and comparisons are unavailable.') },
    { id:'core',title:t('기본 실험실','Core lab'),services:'web · control-plane · demo-api · demo-worker · MySQL · Redis · Kafka',text:t('실제 Java / Spring 서비스의 세션별 장애, 내장 계측 근거와 무료 규칙 기반 RCA를 사용합니다. 비교 부하는 터미널에서 k6로 실행하며 Grafana·검색 로그·분산 추적은 포함하지 않습니다.','Use session-scoped faults in real Java / Spring services, in-process evidence and free rule-based RCA. Run comparison load with k6 in a terminal; Grafana, searchable logs and distributed traces are excluded.') },
    { id:'observability',title:t('관측 도구 포함','With observability'),services:t('기본 7개 + Prometheus · Grafana · Loki · Tempo · OpenTelemetry Collector','Core seven + Prometheus, Grafana, Loki, Tempo and OpenTelemetry Collector'),text:t('기본 기능에 지표 대시보드·검색 로그·분산 추적을 추가합니다. 다운로드·빌드·메모리·디스크 여유가 더 필요합니다. 계정이나 유료 LLM 키는 필수가 아닙니다.','Add metric dashboards, searchable logs and distributed traces. Allow extra download/build time, memory and disk headroom. No account or paid LLM key is required.') },
  ];
  const values=Object.values(draft.ports),valid=values.every(v=>Number.isInteger(v)&&v>=1&&v<=65535)&&new Set(values).size===values.length;
  const portRows=[['CONTROL_PLANE_PORT','Control API',8080],['DEMO_API_PORT',t('상품·주문 API','Catalog/order API'),8081],['DEMO_WORKER_PORT','Worker',8082],['WEB_PORT',t('실험 화면','Experiment UI'),8080],['PROMETHEUS_PORT','Prometheus',9090],['GRAFANA_PORT','Grafana',3000]] as const;
  const up=win ? `.\\scripts\\dev-up.ps1${draft.mode==='observability'?' -Observability':''}` : `bash scripts/dev-up.sh${draft.mode==='observability'?' --observability':''}`;
  const env=Object.entries(draft.ports).map(([k,v])=>`${k}=${v}`).join('\n');
  const compare=win ? `.\\scripts\\demo-compare.ps1 -Scenario CACHE_DEGRADATION -Vus ${draft.vus} -DurationSeconds ${draft.duration}` : `VUS=${draft.vus} DURATION_SECONDS=${draft.duration} bash scripts/demo-compare.sh --scenario CACHE_DEGRADATION`;
  const preparation=win ? 'wsl.exe --list --verbose\ngit --version\ndocker version\ndocker compose version\ndocker info\ndocker system df\nGet-NetTCPConnection -State Listen | Select-Object LocalAddress,LocalPort\nnetsh interface ipv4 show excludedportrange protocol=tcp\nGet-CimInstance Win32_OperatingSystem | Select-Object TotalVisibleMemorySize,FreePhysicalMemory\nGet-PSDrive -PSProvider FileSystem' : 'uname -a\ncat /etc/os-release\ngit --version\ndocker version\ndocker compose version\ndocker info\ndocker system df\nss -ltn\nfree -h\ndf -h';
  return <article className="pc-settings">
    <header className="settings-heading"><span className="learning-kicker">INCIDENTLENS · {t('내 PC 실행 준비','Prepare your local PC')}</span><h1>{t('내 환경에 맞게, 먼저 확인하세요.','Check your environment before you run.')}</h1><p>{t('IncidentLens 자체 실험실의 실행 안내입니다. 임의의 로컬 앱을 자동 분석하거나 원격 서비스에 장애를 설정하는 기능이 아닙니다.','Execution guidance for IncidentLens’s own lab. It does not automatically analyze arbitrary local apps or inject faults into remote services.')}</p></header>
    <div className="settings-draft-note" role="status"><strong>{t('브라우저에 저장한 준비안 · PC에 미적용','Browser-saved plan · not applied to your PC')}</strong><p>{t('아래 선택은 Docker, .env, 실행 중인 서비스와 실험 부하를 변경하지 않습니다. 명령을 읽고 직접 적용해야 합니다.','These choices do not change Docker, .env, running services or experiment load. Review and apply the commands yourself.')}</p>{!stored&&<p>{t('준비안을 저장하지 못했습니다.','The plan could not be saved.')}</p>}</div>
    <fieldset className="settings-mode"><legend>{t('1. 사용 방식 선택','1. Choose how to use the lab')}</legend><div className="mode-cards">{modes.map(m=><label className="mode-card" key={m.id}><input type="radio" name="execution-mode" value={m.id} checked={draft.mode===m.id} onChange={()=>update({...draft,mode:m.id})}/><h2>{m.title}</h2><p>{m.text}</p><small>{t('필요한 구성','Required services')}: {m.services}</small></label>)}</div></fieldset>
    <section className="settings-section"><h2>{t('2. OS / 셸과 실제 준비 상태 확인','2. Choose a shell and check readiness')}</h2><label htmlFor="settings-platform">{t('내가 사용할 OS / 셸 · 자동 감지 아님','The OS / shell I will use · not detected')}<select id="settings-platform" value={platform} onChange={e=>{const p=e.target.value as LearningPlatform;setPlatform(p);try{setStored(savePlatform(localStorage,p));}catch{setStored(false);}}}><option value="windows">Windows · PowerShell</option><option value="linux">Linux / WSL · Bash</option></select></label><p>{t('브라우저는 Docker 엔진·WSL 통합·포트 예약·PC RAM·남은 디스크를 확인하지 못합니다. 아래 명령의 실제 결과를 확인하세요.','The browser cannot inspect the Docker engine, WSL integration, reserved ports, PC RAM or free disk space. Check actual output from these commands.')}</p><details><summary>{t('준비·포트·자원 확인 명령 보기','Show readiness, port and resource commands')}</summary><pre><code>{preparation}</code></pre></details><p>{t('Windows의 WSL에서는 Docker Desktop의 현재 배포판 통합을 확인하세요. 설정 변경이나 재시작 전 기존 컨테이너 영향을 확인하고, 포트 충돌 때 다른 프로세스를 종료하지 마세요.','On WSL, check Docker Desktop integration for your current distribution. Check existing-container impact before settings changes/restarts, and do not kill other processes to reclaim ports.')}</p>{win && <p>{t('PowerShell 스크립트가 실행 정책으로 차단되면 허가와 정책을 먼저 확인하세요. 정책을 자동 변경하거나 우회하지 않습니다. WSL/Bash 실행은 해당 환경 준비를 별도로 확인하세요.', 'If execution policy blocks PowerShell scripts, check authorization and policy first. Nothing automatically changes or bypasses policy. Check WSL/Bash readiness separately.')}</p>}<div className="runtime-readback"><strong>{t('컨트롤 플레인이 보고한 설정','Configuration reported by the control plane')}</strong><p>{runtime ? `${runtime.profile} · ${t('보고된 웹 호스트 포트','declared web host port')} ${runtime.hostPorts.web}` : checked ? t('설정 응답을 받지 못했습니다. 서버가 꺼졌거나 이 조회 API를 지원하지 않을 수 있습니다. Docker 준비 완료를 뜻하지 않습니다.','No configuration response. The server may be offline or may not support this API. This does not establish Docker readiness.') : t('설정 응답을 확인하는 중입니다.','Checking the configuration response.')} {runtime&&t('이 응답은 서버 환경변수의 선언값입니다. 실제 Docker 바인딩과 자원은 터미널에서 확인하세요.','These are declared server environment values. Verify Docker bindings and resources in a terminal.')}</p></div></section>
    <section className="settings-section"><h2>{t('3. 로컬 호스트 포트 준비','3. Plan local host ports')}</h2><p>{t('연결 주소는 127.0.0.1로 제한합니다. 왼쪽 값은 PC에 공개할 호스트 포트이고, 오른쪽은 바꾸지 않는 컨테이너 내부 포트입니다. 충돌·예약 여부는 터미널에서 확인해야 합니다.','Bindings remain on 127.0.0.1. Values on the left are PC host ports; container ports on the right stay unchanged. Check conflicts and reservations in a terminal.')}</p><div className="table-scroll"><table className="settings-port-table"><thead><tr><th>{t('환경변수 · 서비스','Variable · service')}</th><th>{t('호스트 포트 · 준비안','Host port · plan')}</th><th>{t('컨테이너 내부','Inside container')}</th></tr></thead><tbody>{portRows.map(([k,label,internal])=><tr key={k}><td><code>{k}</code><small>{label}</small></td><td><input type="number" min="1" max="65535" aria-label={`${k} ${t('호스트 포트','host port')}`} value={draft.ports[k]} onChange={e=>update({...draft,ports:{...draft.ports,[k]:Number(e.target.value)}})}/></td><td>{internal}</td></tr>)}</tbody></table></div>{!valid&&<p role="alert">{t('포트는 서로 다른 1–65535 정수로 입력하세요. 유효한 준비안이 될 때까지 적용 명령을 표시하지 않습니다.','Use distinct integer ports from 1 to 65535. Apply commands are hidden until the plan is valid.')}</p>}<p>{t('예상 주소 · 아직 적용되지 않음','Planned addresses · not applied')}: http://127.0.0.1:{draft.ports.WEB_PORT} · API http://127.0.0.1:{draft.ports.CONTROL_PLANE_PORT}</p></section>
    <section className="settings-section"><h2>{t('4. 메모리 한도와 작은 부하','4. Memory limits and a small workload')}</h2><p>{t('현재 고정 Compose 한도(MiB): Java 앱 각각 640, MySQL 768, Redis 128, Kafka 896, 웹 128. 관측 도구는 Prometheus 384, Grafana 256, Loki 384, Tempo 1024, Collector 512입니다. 임의의 낮은 메모리 설정은 이 화면에서 제공하지 않습니다.','Current fixed Compose limits (MiB): each Java app 640, MySQL 768, Redis 128, Kafka 896 and web 128. Observability: Prometheus 384, Grafana 256, Loki 384, Tempo 1024 and Collector 512. This page offers no unverified low-memory settings.')}</p><p>{t('기본 한도 합계는 3.75 GiB, 관측 포함은 6.25 GiB입니다. 실제 사용량이나 최소사양이 아니며 Docker·OS·이미지 빌드에는 별도 여유가 필요합니다. Docker 가용 메모리 약 6/8 GB는 계획용 추정치일 뿐 저사양 정상 동작 검증이 아닙니다.','The limits sum to 3.75 GiB for core and 6.25 GiB with observability. These are neither measured use nor minimum requirements. Docker, the OS and image builds need extra headroom. Roughly 6/8 GB available to Docker are planning estimates, not verified low-spec requirements.')}</p><div className="settings-load"><label htmlFor="settings-vus">{t('동시 사용자 · 기본 2, 허용 1–50','Virtual users · default 2, allowed 1–50')}<input id="settings-vus" type="number" min="1" max="50" value={draft.vus} onChange={e=>update({...draft,vus:Number(e.target.value)})}/></label><label htmlFor="settings-duration">{t('단계별 시간(초) · 기본 10, 허용 5–300','Seconds per phase · default 10, allowed 5–300')}<input id="settings-duration" type="number" min="5" max="300" value={draft.duration} onChange={e=>update({...draft,duration:Number(e.target.value)})}/></label></div><p>{t('처음에는 2 VUs × 단계별 10초로 작게 시작하고 docker stats와 응답 오류·대기열을 관찰하세요. 허용 최대값은 PC가 감당한다는 보장이 아닙니다. 실행시간은 종료 대기를 포함해 설정한 부하 시간보다 길 수 있습니다.','Begin with 2 VUs for 10 seconds per phase and observe docker stats, errors and backlogs. Allowed maxima are not capacity guarantees. Elapsed runtime may exceed configured workload duration due to graceful completion.')}</p></section>
    <section className="settings-section"><h2>{t('5. 직접 적용할 명령','5. Commands to apply yourself')}</h2>{draft.mode==='frontend'?<><p>{t('기존 Docker 서비스를 종료하지 않고 프런트엔드만 실행합니다. --mode ui은 이 개발 서버의 실험 API 프록시를 차단합니다.','Run the frontend without stopping existing Docker services. --mode ui blocks this dev server’s experiment API proxy.')}</p><pre><code>{`cd apps/web\n${win ? 'npm.cmd' : 'npm'} ci\n${win ? 'npm.cmd' : 'npm'} run dev -- --host 127.0.0.1 --port 5173 --mode ui`}</code></pre><p>http://127.0.0.1:5173</p></>:valid?<><p>{t('기존 .env를 보존하면서 아래 포트 항목만 편집하세요. 명령은 저장소 루트에서 실행합니다. 변경한 환경변수·포트·프로필은 Compose up으로 해당 컨테이너를 재생성해야 적용됩니다. 단순 restart는 새 .env를 읽지 않습니다.','Preserve the existing .env and edit only these port entries. Run commands at the repository root. Changed environment, ports and profile require Compose up to recreate affected containers; restart alone does not reread .env.')}</p><pre><code>{env}</code></pre><pre><code>{up+'\n'+(win?'.\\scripts\\dev-status.ps1':'bash scripts/dev-status.sh')}</code></pre>{draft.vus>=1&&draft.vus<=50&&Number.isInteger(draft.vus)&&draft.duration>=5&&draft.duration<=300&&Number.isInteger(draft.duration)&&<><h3>{t('명시적으로 비교 부하를 실행할 때만','Only when explicitly running comparison load')}</h3><pre><code>{compare}</code></pre></>}<p>{t('관측 모드에서 기본 모드로 전환해도 기존 관측 컨테이너를 자동 삭제하지 않습니다. 자원을 줄이려면 관측 서비스 다섯 개만 명시적으로 stop하세요. 데이터·볼륨 초기화는 필요 없습니다.','Switching to core does not automatically remove existing observability containers. To reduce resource use, explicitly stop only those five services. No data or volume reset is needed.')}</p></>:null}<div className="settings-safety"><strong>{t('한 로컬 실험실만 대상으로 실행합니다.','Run against one matched local lab.')}</strong><p>{t('비교 실행기는 CONTROL_URL, Compose 바인딩, 컨트롤 플레인 식별자와 내부 demo-api/worker·k6 대상을 확인합니다. 주소만 바꾸거나 구성이 다르면 세션·장애·부하 실행 전에 중단합니다. 원격 실험은 지원하지 않습니다.','The comparison runner checks CONTROL_URL, Compose bindings, control-plane identity and internal demo-api/worker and k6 targets. Address-only changes or mismatched configuration stop before creating a session, setting a fault or running load. Remote experiments are unsupported.')}</p><p>{t('새 비교 결과는 실제 실행 구성·부하·시간 구간을 저장합니다. PC 자원·다른 트래픽·캐시 온도는 자동으로 동일해지지 않으므로 다른 PC 결과를 같은 조건의 성능으로 비교하지 마세요.','New comparison results record actual execution configuration, load and time windows. PC resources, other traffic and cache warmth do not become equal automatically; do not compare different PCs as equivalent benchmark conditions.')}</p></div></section>
  </article>;
}
