import type { Chapter, Copy, PhaseId } from "./language-course";
const b = (ko: string, en: string): Copy => ({ ko, en });
const ch = (intro: Copy, flow: Copy, code: string, codeScope: Copy, failure: Copy, guided: Copy, independent: Copy, source: string): Chapter =>
  ({ intro, flow, code, codeScope, failure, guided, independent, source });
export const moreCourses: { go: Record<PhaseId, Chapter>; csharp: Record<PhaseId, Chapter> } = {
  go: {
    api: ch(
      b("Go의 net/http는 표준 라이브러리로 요청 핸들러를 만듭니다. 경로·메서드·JSON·HTTP 상태를 명시적으로 다룹니다.", "Go net/http creates request handlers using the standard library. Handle path, method, JSON and HTTP status explicitly."),
      b("GET /products/1 → mux → handler → 상품 조회 → JSON/404. 요청 context를 DB 호출에 전달해 취소/시간 제한을 잇습니다.", "GET /products/1 → mux → handler → product lookup → JSON/404. Pass request context to DB work for cancellation/deadline."),
      "mux := http.NewServeMux()\nmux.HandleFunc(\"GET /products/{id}\", func(w http.ResponseWriter, r *http.Request) {\n  id := r.PathValue(\"id\")\n  if id != \"1\" { http.NotFound(w, r); return }\n  w.Header().Set(\"Content-Type\", \"application/json\")\n  _, _ = w.Write([]byte(`{\"id\":1,\"price\":1200}`))\n})",
      b("Go 1.22+ ServeMux 패턴을 쓰는 초점 코드입니다. 패키지/import/server 시작과 쓰기 오류 처리를 생략했고 이 저장소에서 실행하지 않았습니다.", "Focused Go 1.22+ ServeMux pattern. Package/import/server startup and write-error handling are omitted; it was not run here."),
      b("404는 경로 또는 상품 없음, 405는 메서드, 500은 내부 실패로 나눕니다. 응답 헤더를 본문 쓰기 전에 정합니다.", "Separate 404 route/product missing, 405 method and 500 internal error. Set headers before writing the body."),
      b("GET /products/1과 /products/2의 응답을 예측하고 메서드를 POST로 바꾼 경우도 확인하세요.", "Predict GET /products/1 and /products/2 and what changes for POST."),
      b("수량 검증이 있는 POST /orders를 설계하고 handler와 주문 Service의 책임을 나누세요.", "Design POST /orders quantity validation and split handler from order service."),
      "https://go.dev/blog/routing-enhancements"),
    db: ch(
      b("Go database/sql은 연결 풀과 트랜잭션 경계를 제공하지만 실제 DB 드라이버는 따로 필요합니다. 주문과 outbox는 같은 Tx로 처리합니다.", "Go database/sql provides a connection pool and transaction boundary but requires a DB driver. Order and outbox share one Tx."),
      b("HTTP 입력 → DB.BeginTx(ctx) → parameterized order INSERT → outbox INSERT → Commit → 201. 실패 시 Rollback; context 취소도 처리합니다.", "HTTP input → DB.BeginTx(ctx) → parameterized order INSERT → outbox INSERT → Commit → 201. Roll back on failure and handle context cancellation."),
      "tx, err := db.BeginTx(ctx, nil)\nif err != nil { return err }\ndefer tx.Rollback()\n_, err = tx.ExecContext(ctx, \"INSERT INTO orders(id) VALUES(?)\", orderID)\nif err != nil { return err }\n_, err = tx.ExecContext(ctx, \"INSERT INTO outbox(order_id) VALUES(?)\", orderID)\nif err != nil { return err }\nreturn tx.Commit()",
      b("database/sql 트랜잭션 초점 코드입니다. ? placeholder는 선택 DB/드라이버에 따라 다릅니다. schema, driver, 함수 문맥이 없으며 실행하지 않았습니다.", "Focused database/sql transaction. Placeholder syntax varies by DB/driver; schema, driver and function context are omitted and it was not run."),
      b("SQL 문자열 결합으로 외부 ID를 넣지 않습니다. 두 INSERT가 같은 Tx인지, Commit 오류와 Rollback 경로, 연결 풀 한도를 확인합니다.", "Do not concatenate external IDs into SQL. Check both INSERTs use one Tx, commit/rollback paths and pool limits."),
      b("둘째 INSERT 실패와 Commit 실패를 구분해 남는 데이터와 재시도 규칙을 적으세요.", "Differentiate second INSERT failure and commit failure; predict data and retry rules."),
      b("동시 요청의 같은 주문 키를 unique constraint로 지키고 오류를 안전한 HTTP 결과로 변환하세요.", "Protect duplicate order keys with a unique constraint and map conflicts to safe HTTP outcomes."),
      "https://go.dev/doc/database/execute-transactions"),
    auth: ch(
      b("Go handler/middleware는 사용자 신원을 검증하고 주문 소유권 검사는 업무 조회에 연결합니다. 사용자 ID를 요청자가 보낸 URL만으로 믿지 않습니다.", "Go handler/middleware verifies identity and business lookup checks order ownership. Never trust a user ID supplied only in the URL."),
      b("Authorization Bearer → 검증 함수가 서명·만료·issuer·audience 확인 → context에 사용자 ID → DB에서 소유 주문 조회 → 401/403/200.", "Authorization Bearer → verifier checks signature, expiry, issuer, audience → user ID in context → owner-scoped DB query → 401/403/200."),
      "userID, err := verifyBearer(r.Header.Get(\"Authorization\"))\nif err != nil { http.Error(w, \"unauthorized\", 401); return }\norder, err := findOrderForOwner(r.Context(), orderID, userID)\n// no matching owned order: do not reveal another user's data",
      b("보안 검증 함수·키 관리·DB 함수가 없는 설계 조각입니다. 이 자체로 실행 가능한 인증이 아니며 개인정보 노출 정책에 따라 403/404를 정해야 합니다.", "Design fragment without verifier/key management/DB implementation. It is not runnable authentication; choose 403/404 disclosure policy explicitly."),
      b("헤더 문자열을 로깅하지 말고 검증 대상·만료를 확인합니다. 소유자 조회 누락은 수평 권한 상승입니다.", "Never log header contents; check audience and expiry. An omitted owner filter is horizontal privilege escalation."),
      b("토큰 없음·만료·다른 소유자의 주문을 순서대로 처리하는 미들웨어 흐름을 그리세요.", "Draw middleware flow for missing token, expired token and another user's order."),
      b("사용자 ID를 URL로 바꾸어 남의 주문을 읽지 못하게 할 DB 쿼리와 테스트를 설계하세요.", "Design query and test preventing access to others' orders by changing a URL user ID."),
      "https://pkg.go.dev/net/http"),
    tests: ch(
      b("Go testing 패키지로 순수 계산을, httptest로 HTTP 상태/본문을, 격리 DB로 트랜잭션을 각각 확인합니다.", "Use Go testing for pure calculations, httptest for HTTP status/body, and an isolated DB for transactions."),
      b("테스트 handler → httptest 요청/Recorder → status/JSON 검사. 저장 경계 테스트는 실제 드라이버·격리 DB와 rollback/행 수 검사가 필요합니다.", "Test handler → httptest request/Recorder → assert status/JSON. Persistence boundary tests need a driver, isolated DB and rollback/row checks."),
      "req := httptest.NewRequest(http.MethodGet, \"/products/2\", nil)\nrec := httptest.NewRecorder()\nmux.ServeHTTP(rec, req)\nif rec.Code != http.StatusNotFound { t.Fatalf(\"got %d\", rec.Code) }",
      b("testing/httptest의 초점 테스트 조각입니다. mux와 t를 만든 테스트 함수가 필요하며 이 저장소에서는 실행하지 않았습니다.", "Focused testing/httptest fragment requiring a test function with mux and t; not run in this repository."),
      b("요청 순서에 따라 실패하면 공유 상태를, race 우려는 별도 race detector 실행을, DB 테스트 통과 범위는 드라이버와 엔진을 확인합니다.", "For order-dependent failures inspect shared state; use race detector separately for races; report DB test scope by driver/engine."),
      b("존재/부재 상품 두 httptest 계약을 작성하세요.", "Write two httptest contracts for present and missing products."),
      b("주문+outbox 커밋 불변식과 중복 키 동시성 테스트의 관측 기준을 설계하세요.", "Design observable invariants for order+outbox commit and concurrent duplicate keys."),
      "https://go.dev/doc/tutorial/add-a-test"),
    deployment: ch(
      b("Go를 빌드해도 설정·비밀·DB migration·health·로그·종료 동작·롤백은 별도입니다. 대상 OS/아키텍처에 맞는 바이너리여야 합니다.", "A compiled Go binary still needs config/secrets, DB migrations, health, logs, shutdown and rollback. Binary target OS/architecture must match."),
      b("대상 환경 지정·빌드 → schema 적용 → 환경 주입 → 서버 실행/readiness → 트래픽 → 오류/지연 관측 → 롤백.", "Set target/build → migrate schema → inject env → run/readiness → traffic → observe errors/latency → rollback."),
      "go build -o catalog .       # Linux/macOS target\ngo build -o catalog.exe .   # Windows target\n# build for the target OS; not executed here",
      b("프로젝트 모듈·전체 코드가 없어 실행 가능한 배포 명령은 아닙니다. Windows/Linux 파일 이름 차이를 보이는 예시이며 교차 컴파일 설정은 별도입니다.", "No complete module/source is supplied, so this is not a runnable deployment. It shows Windows/Linux naming; cross-compilation needs separate settings."),
      b("exec format error는 대상 OS/CPU를, 준비 실패는 포트/DB, 요청 중단은 timeout과 graceful shutdown을 확인합니다.", "For exec-format errors inspect target OS/CPU; for readiness failures port/DB; for dropped requests timeout and graceful shutdown."),
      b("SIGTERM 뒤 새 요청을 막고 진행 요청과 DB 연결을 마칠 순서를 적으세요.", "Plan how SIGTERM stops new requests and drains in-flight work/DB connections."),
      b("새 schema와 구 버전 바이너리가 함께 있는 기간의 호환·롤백 절차를 설계하세요.", "Design compatibility/rollback while old binary and new schema coexist."),
      "https://go.dev/doc/tutorial/compile-install"),
  },
  csharp: {
    api: ch(
      b("C#의 ASP.NET Core Minimal API는 경로와 함수를 연결합니다. .NET SDK, C# 언어, ASP.NET Core 웹 프레임워크를 구분하세요.", "ASP.NET Core Minimal API maps routes to functions. Distinguish .NET SDK, C# language and ASP.NET Core framework."),
      b("GET /products/1 → MapGet handler → ID 타입 변환 → 서비스/상품 조회 → Results.Ok/NotFound. 잘못된 요청과 없는 자원을 구분합니다.", "GET /products/1 → MapGet handler → typed ID → service/product lookup → Results.Ok/NotFound. Separate invalid input from missing resource."),
      "var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\napp.MapGet(\"/products/{id:int}\", (int id) =>\n  id == 1 ? Results.Ok(new { Id = 1, Price = 1200 })\n          : Results.NotFound());\napp.Run();",
      b("ASP.NET Core 웹 프로젝트 Program.cs의 초점 코드입니다. 고정 상품이며 DB/인증 없이 여기서 실행하지 않았습니다.", "Focused Program.cs for an ASP.NET Core web project. It uses a fixed product, with no DB/auth, and was not run here."),
      b("404 경로 미일치와 상품 부재를 구분하고 500이면 DI/서비스 오류를 봅니다. 바인딩 규칙을 API 계약과 맞춥니다.", "Separate route mismatch from missing product for 404, and inspect DI/service errors for 500. Align binding with API contract."),
      b("ID 1/2/문자의 예상 상태를 경로 제약과 비교하세요.", "Compare predicted statuses for ID 1/2/text with route constraint."),
      b("POST /orders 요청 모델과 수량 규칙을 설계하고 접수 응답을 후속 완료와 구분하세요.", "Design POST /orders request model and quantity rule; separate accepted from later fulfillment."),
      "https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api"),
    db: ch(
      b("EF Core는 C# 객체를 관계형 DB에 매핑하지만 DB 제약과 실제 SQL 검토를 대신하지 않습니다. 주문·outbox를 한 SaveChanges/트랜잭션 경계에 둡니다.", "EF Core maps C# objects to a relational DB but does not replace constraints or SQL review. Keep order/outbox in one SaveChanges/transaction boundary."),
      b("HTTP 입력 → DbContext에서 상품 조회 → 주문·outbox 추가 → SaveChangesAsync → 결과. 별도 외부 발행은 커밋 뒤 relay가 맡습니다.", "HTTP input → query product with DbContext → add order/outbox → SaveChangesAsync → result. A relay publishes externally after commit."),
      "db.Orders.Add(new Order { Id = orderId, ProductId = productId });\ndb.Outbox.Add(new OutboxEvent { OrderId = orderId });\nawait db.SaveChangesAsync(cancellationToken);",
      b("EF Core 모델·DbContext·provider/schema가 정의됐다는 전제의 초점 코드입니다. 실제 DB/마이그레이션 없이 실행되지 않았습니다.", "Focused code assuming EF Core models, DbContext, provider and schema. It was not run against a DB/migration."),
      b("예외가 나면 두 행이 모두 없는지 확인하고 unique index·SQL·provider를 봅니다. SaveChanges 여러 번을 한 트랜잭션이라고 가정하지 않습니다.", "On exception confirm neither row persists and inspect unique index/SQL/provider. Do not assume separate SaveChanges calls form one transaction."),
      b("상품 없음과 outbox 쓰기 실패에 남아야 하는 행을 표로 쓰세요.", "Tabulate persisted rows for missing product and failed outbox write."),
      b("중복 주문 키 unique index와 동시 요청에서 결과를 200/201/409로 나누는 규칙을 설계하세요.", "Design a unique order-key index and 200/201/409 outcomes for concurrent requests."),
      "https://learn.microsoft.com/en-us/ef/core/saving/transactions"),
    auth: ch(
      b("ASP.NET Core 인증은 신원을 설정하고 권한 검사는 특정 주문 접근을 판단합니다. RequireAuthorization을 붙여도 리소스 소유권 검사는 별개입니다.", "ASP.NET Core authentication identifies the caller; authorization decides access. RequireAuthorization alone does not check order ownership."),
      b("Bearer 토큰 → JWT handler가 issuer/audience/서명/만료 검증 → 사용자 claim → order.ownerId 비교 → 401/403/200.", "Bearer token → JWT handler validates issuer/audience/signature/expiry → user claim → compare order.ownerId → 401/403/200."),
      "builder.Services.AddAuthentication().AddJwtBearer();\nbuilder.Services.AddAuthorization();\n// configure trusted issuer/audience/key outside this sketch\napp.MapGet(\"/orders/{id}\", handler).RequireAuthorization();",
      b("필수 신뢰 설정, middleware 순서, handler 소유권 검사를 생략한 설계 조각입니다. 안전하게 실행 가능한 인증 프로젝트가 아닙니다.", "Design sketch omitting trusted settings, middleware ordering and handler ownership check. Not a safe runnable authentication project."),
      b("401 무효 신원과 403 소유권 거부를 구분합니다. 설정되지 않은 issuer/key 또는 누락된 ownership 검사로 보호를 주장하지 않습니다.", "Separate 401 invalid identity from 403 denied ownership. Do not claim protection without configured issuer/key and ownership check."),
      b("자신/타인/만료 토큰에서 사용자 claim과 주문 소유자를 어떻게 비교할지 적으세요.", "Describe claim-versus-order-owner checks for own, other and expired token."),
      b("주문 ID 변경만으로 타인의 결과를 읽지 못하는 정책·DB 조회·테스트를 설계하세요.", "Design policy, owner-scoped lookup and tests blocking another user's order via ID changes."),
      "https://learn.microsoft.com/en-us/aspnet/core/security/authentication/"),
    tests: ch(
      b("xUnit 같은 테스트 도구로 순수 규칙을 검사하고 WebApplicationFactory로 HTTP 변환을, 별도 DB 경계 테스트로 트랜잭션을 봅니다.", "Use xUnit-like tooling for pure rules, WebApplicationFactory for HTTP mapping and separate DB boundary tests for transactions."),
      b("격리 앱 factory → HttpClient 요청 → status/body 확인 → 격리 DB에서 order/outbox 불변식 확인.", "Isolated app factory → HttpClient request → assert status/body → check order/outbox invariants in isolated DB."),
      "var response = await client.GetAsync(\"/products/999\");\nAssert.Equal(HttpStatusCode.NotFound, response.StatusCode);",
      b("테스트 client, xUnit, WebApplicationFactory와 프로젝트 참조가 필요합니다. 이 저장소에서 컴파일/실행한 C# 테스트가 아닙니다.", "Needs test client, xUnit, WebApplicationFactory and project references. No C# test was compiled/run in this repository."),
      b("InMemory provider 통과를 실제 관계형 제약 검증으로 해석하지 않습니다. HTTP/DB 테스트가 어떤 경계를 썼는지 기록합니다.", "Do not treat an InMemory provider pass as relational-constraint verification. Record which boundary each HTTP/DB test exercises."),
      b("정상·없는 상품의 응답과 수량 오류 계약을 적으세요.", "Write response contracts for existing/missing product and invalid quantity."),
      b("중복 키 동시 주문과 DB rollback을 검증할 관계형 테스트/행 수 기준을 설계하세요.", "Design relational tests and row-count criteria for concurrent duplicate keys and DB rollback."),
      "https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests"),
    deployment: ch(
      b(".NET 앱은 publish 산출물과 target runtime, 환경·비밀, DB migration, health/readiness, 로그·롤백을 관리해야 합니다.", ".NET deployment needs publish artifact/target runtime, env/secrets, DB migration, health/readiness, logs and rollback."),
      b("dotnet publish → 산출물/설정 배치 → schema 적용 → 프로세스 시작/readiness → 트래픽 → 오류·지연 감시 → 롤백.", "dotnet publish → place artifact/config → migrate schema → process/readiness → traffic → watch errors/latency → rollback."),
      "dotnet publish -c Release\n# Windows PowerShell and Linux Bash; target runtime/hosting still need configuration",
      b("프로젝트가 있을 때 Windows/Linux 모두 사용할 수 있는 명령 형태입니다. 여기에는 C# 프로젝트가 없고 실행하지 않았습니다.", "Command shape for a project on Windows PowerShell or Linux Bash. No C# project exists here; not run."),
      b("시작 실패는 runtime/환경/포트, 502는 호스트↔프로세스, DB 오류는 migration과 연결 문자열을 확인합니다.", "For startup inspect runtime/env/port; for 502 host↔process; for DB errors migrations and connection string."),
      b("readiness가 DB 접근을 확인하더라도 개별 주문 성공을 보장하지 못하는 이유를 적으세요.", "Explain why DB readiness does not guarantee individual order success."),
      b("구/신 버전이 함께 실행되는 동안의 schema 확장·축소와 rollback 순서를 설계하세요.", "Design expand/contract schema rollout and rollback while old and new versions overlap."),
      "https://learn.microsoft.com/en-us/dotnet/core/deploying/"),
  },
};
