import type { LanguageStage } from './language-depth-data';
import type { CodeLanguage } from './programming-tracks';
const b = (ko: string, en: string) => ({ ko, en });
const practice = {
  tools: b('입문 프로젝트 폴더에서 버전 확인→파일 위치 확인→검사→서버 실행 순서로 진행합니다. PORT를 비어 있는 포트로 정하고 /health를 호출한 뒤 자기 프로세스만 Ctrl+C로 종료합니다. IncidentLens 자체는 Java 21/Gradle과 Compose로 실행합니다.', 'In the intro directory check runtime version, locate files, run tests, then serve. Choose an unused PORT, call /health, and stop your process with Ctrl+C. IncidentLens itself runs with Java 21/Gradle and Compose.'),
  basics: b('가격 1200×수량 2=2400을 순수 함수로 분리하고 0, 1, 100, 101, 문자열 입력을 검사합니다. Python은 bool도 int의 하위형이므로 type 확인, JS는 Number.isInteger, C#은 정수 DTO와 범위 검사를 구분합니다. 타입 표기만으로 HTTP JSON이 안전해지지는 않습니다.', 'Separate the pure 1200×2=2400 calculation and test 0, 1, 100, 101 and string input. Python must account for bool being an int subclass; JS uses Number.isInteger; C# separates integer DTO binding from range checks. Types alone cannot validate HTTP JSON.'),
  http: b('입문 서버의 /products/1(200), /products/9(404), 잘못된 수량(400)을 실제 요청해 상태와 본문을 기록합니다. 같은 멱등 키/본문은 200과 같은 주문 ID, 다른 본문은 409입니다. 이 단계의 메모리 주문은 재시작하면 사라지며 자유실험실 결과로 표시하지 않습니다.', 'Call the intro /products/1 (200), /products/9 (404) and invalid quantity (400); record status/body. Same idempotency key/body gives 200 and the same order ID; changed body gives 409. Intro memory orders vanish on restart and are not free-lab results.'),
  api: b('고급 API의 route→입력 검증→Store.Create/create→응답 경계를 따라갑니다. FastAPI/Pydantic의 422, Express의 명시적 400, ASP.NET의 바인딩 400/라우트 404는 계약 차이입니다. 토큰·본문 오류·DB 실패를 같은 상태로 감추지 마세요. 자유실험실의 대응 코드는 demo-api Controller/Service입니다.', 'Follow the advanced route → validation → Store.Create/create → response. FastAPI/Pydantic 422, explicit Express 400, and ASP.NET binding 400/route 404 differ by contract. Keep token, input and store failures distinguishable. The free-lab counterpart is demo-api Controller/Service.'),
  persistence: b('PRACTICE_DB를 새 파일로 지정해 주문을 저장하고 API를 종료·재시작한 뒤 같은 ID를 조회합니다. schema.sql의 기본키·외래키·unique를 찾아보세요. API와 worker를 멈춘 뒤 advanced에서 python3 migrate.py --db <연습DB> up으로 description 열을 추가하고 down으로 되돌립니다. 주문/가격 보존을 검사합니다. 실제 실험실은 MySQL/Flyway이며 SQLite 되돌리기 성공은 MySQL 검증이 아닙니다.', 'Save an order in a fresh PRACTICE_DB; stop/restart the API and read the same ID. Locate primary/foreign/unique keys in schema.sql. Stop API/worker; from advanced run python3 migrate.py --db <practiceDB> up to add description, then down to remove it. Check order/price preservation. The real lab uses MySQL/Flyway; SQLite rollback does not verify MySQL.'),
  transactions: b('Store의 주문 INSERT 바로 뒤 failAfterOrder/fail_after_order를 주입한 검사를 실행합니다. 주문 수와 outbox 수가 모두 0이어야 합니다. 재시작 뒤 정상 주문과 outbox가 함께 남는지도 검사합니다. commit 전 예외는 rollback, commit 후 HTTP 응답 유실은 같은 키로 재시도합니다. 실제 demo-api의 주문+outbox 트랜잭션과 비교하세요.', 'Run the Store test injecting failAfterOrder/fail_after_order just after INSERT. Both order and outbox counts must be zero. Check both survive a successful commit/restart. Roll back exceptions before commit; retry a lost HTTP response after commit with the same key. Compare with demo-api order+outbox transaction.'),
  security: b('서로 다른 임의 토큰을 셸에서만 준비합니다. 토큰 없음/무효는 401, alice 주문을 bob이 읽으면 403, alice는 200을 확인합니다. 이 신원표는 서명·만료·로그인 검증이 없습니다. 실제 IncidentLens는 로컬 장애 실험실이며 이 예제 인증 기능을 갖춘 것으로 표현하지 않습니다. 공개 배포에서는 OIDC 등 검증된 신원을 별도로 연결합니다.', 'Supply distinct random tokens only in the shell. Verify absent/invalid token 401, bob reading alice’s order 403, and alice 200. This fixture has no signature, expiry or login verification. IncidentLens is a local fault lab, not an implementation of this exercise auth. Public deployment needs a verified identity provider such as OIDC.'),
  testing: b('단위 함수→Store rollback/replay→HTTP 401/403→프로세스 복구 순서로 실패 범위를 좁힙니다. advanced/verify_recovery.py는 Python·JS·컴파일된 TS의 실제 프로세스를 실행하고 C# HttpTests는 같은 경계를 HTTP로 검사합니다. H2·SQLite·실제 MySQL 검사는 서로 다른 증거입니다.', 'Narrow failures through pure units → Store rollback/replay → HTTP 401/403 → process recovery. advanced/verify_recovery.py starts real Python, JS and compiled TS processes; C# HttpTests checks the same boundary over HTTP. H2, SQLite and real MySQL checks are different evidence.'),
  collaboration: b('Python requirements.lock, JS package-lock.json, C# packages.lock.json을 사용합니다. npm ci, pip install -r requirements.lock, dotnet restore --locked-mode 뒤 검사합니다. TS는 npm run build/typecheck와 컴파일된 서버의 HTTP 결과까지 확인합니다. .github/workflows/ci.yml의 언어 예제 job을 읽고 로컬 결과와 CI 결과를 구분하세요.', 'Use requirements.lock, package-lock.json and packages.lock.json. Check after npm ci, pip install -r requirements.lock or dotnet restore --locked-mode. TS needs build/typecheck plus HTTP results from the compiled server. Read the language example job in .github/workflows/ci.yml; distinguish local from CI results.'),
  operations: b('worker를 끈 채 주문을 접수해 accepted와 pending을 확인→API Ctrl+C→같은 DB로 재시작→같은 키로 200 재생→worker 시작→fulfilled를 확인합니다. worker도 종료·재시작해 같은 이벤트 효과가 다시 생기지 않는지 검사합니다. DB 변경 전 임시 DB 복사본을 만들고 up/down 후 데이터 보존을 확인하세요. 실제 운영의 TLS·다중 서버·롤백은 별도 설계가 필요합니다.', 'With worker stopped, accept an order and check accepted/pending → Ctrl+C API → restart on same DB → replay key for 200 → start worker → check fulfilled. Stop/restart the worker and check no repeated event effect. Copy the temporary DB before up/down and verify data preservation. Production TLS, replicas and release rollback require separate design.'),
  observability: b('POST 응답의 X-Request-Id와 API 로그 requestId를 기록하고 outbox.request_id→worker 로그 requestId/orderId/eventId를 연결합니다. 재생 요청에는 새 요청 ID가 생겨도 최초 주문의 outbox ID는 유지됩니다. /metrics는 로컬 JSON이며 Prometheus 형식이나 trace가 아닙니다. 실제 실험실의 Prometheus→Grafana, OTel→Loki/Tempo 경로는 관련 기술 안내에서 비교하세요.', 'Join POST X-Request-Id and API requestId through outbox.request_id to worker requestId/orderId/eventId. A replay gets a new request ID while the original order’s outbox ID remains. /metrics is local JSON, not Prometheus exposition or tracing. Compare real lab Prometheus→Grafana and OTel→Loki/Tempo through the related guides.'),
  performance: b('상품을 두 번 읽어 cache hit/miss와 원본 읽기 수를 비교하고 TTL 만료 검사로 오래된 값 재사용을 막습니다. 상품 수정은 현재 구현 범위 밖이며 추가할 때 쓰기 후 무효화가 필요합니다. 작은 앱은 DB 인덱스만으로 충분할 수 있습니다. 실제 Redis 공유 캐시와 장애 시 DB fallback은 demo-api CatalogService와 Redis 통합 검사에서 확인합니다.', 'Read a product twice and compare cache hit/miss/source reads; verify reload after TTL. Product editing is outside this implementation; add invalidation after writes when extending it. A DB index may suffice for small apps. Real Redis/shared cache and outage fallback live in demo-api CatalogService and Redis integration tests.'),
  concurrency: b('SQLite의 BEGIN IMMEDIATE/트랜잭션과 unique(owner,idempotency_key)가 조회+생성 경계를 보호합니다. 같은 사용자/키/본문은 기존 ID, 다른 본문은 409, 다른 사용자는 별도 주문입니다. 네트워크 재시도를 재현하고 주문 행 수를 확인하세요. 5초 busy timeout은 무한 재시도 보장이 아닙니다. 실제 MySQL 경합·여러 서버 보장은 통합 검사로 따로 확인합니다.', 'SQLite BEGIN IMMEDIATE/transactions and unique(owner,idempotency_key) protect lookup+create. Same owner/key/body replays the ID; changed body gives 409; another owner gets another order. Reproduce network retry and check row count. A five-second busy timeout is not indefinite resilience. Verify actual MySQL contention/replicas separately.'),
  messaging: b('worker 중지→201 accepted→pending 1→worker 실행→fulfilled/pending 0→worker 재시작 순서를 직접 기록합니다. processed_event unique와 상태 갱신이 같은 트랜잭션인지 확인하세요. polling 실패는 대기 후 재시도하지만 Kafka offset, broker DLQ, 분산 전달을 구현하지 않습니다. 실제 Kafka outbox relay·consumer·DLQ와 비교하며 작은 작업은 DB 작업표로도 충분한 이유를 설명하세요.', 'Record stopped worker → 201 accepted → pending 1 → worker start → fulfilled/pending 0 → worker restart. Verify processed_event uniqueness and status update share a transaction. Polling retries after failure but implements no Kafka offset, broker DLQ or distributed delivery. Compare real Kafka relay/consumer/DLQ and explain when a DB job table suffices.'),
  capstone: b('예제를 복사하는 데서 끝내지 말고 두 번째 상품과 가격 변경·캐시 무효화, 권한 실패, DB rollback, 동시 중복 요청, worker 복구를 독립적으로 추가하세요. 명령/입력/예상/실제 결과와 한계를 제출합니다. Redis/Kafka를 선택한다면 실제 연결·장애 검사를 추가하고 SQLite 모형의 통과를 대체 증거로 쓰지 않습니다.', 'Independently extend a second product, price edits/cache invalidation, denied access, DB rollback, concurrent replay and worker recovery. Submit commands, inputs, expected/actual results and limits. If choosing Redis/Kafka, add actual connection/failure checks; passing SQLite models cannot substitute for them.'),
} satisfies Record<LanguageStage, { ko: string; en: string }>;
export function stagePractice(stage: LanguageStage, language: Exclude<CodeLanguage, 'java'>) {
  const runtime = {python:'FastAPI · sqlite3',javascript:'Express · node:sqlite · compiled TypeScript',csharp:'ASP.NET Core · Microsoft.Data.Sqlite'}[language];
  return b(`${runtime}: ${practice[stage].ko}`, `${runtime}: ${practice[stage].en}`);
}
