import { useState } from 'react';
import type { KeyboardEvent } from 'react';
import type { CodeLanguage } from './programming-tracks';
import { codeLanguages } from './programming-tracks';
import { languageStages, type LanguageStage } from './language-depth-data';
import { javaStage, type TrackRecord } from './track-state';
import type { TrackChapter } from './track-content';
import type { Locale } from '../i18n/translations';
import LessonText from './LessonText';
import KnowledgeCheck from './KnowledgeCheck';
const tabs = [['concept', '개념', 'Concept'], ['example', '예제', 'Examples'], ['flow', '흐름과 메모', 'Flow & notes'], ['practice', '실습', 'Practice'], ['troubleshoot', '오류 해결', 'Troubleshooting'], ['check', '자기 확인', 'Self-review']] as const;
type Tab = typeof tabs[number][0];
export default function TrackLesson({ language, locale, chapter: c, record: r, update, select, saved }: {
  language: CodeLanguage; locale: Locale; chapter: TrackChapter; record: TrackRecord; saved: boolean; update: (r: TrackRecord) => void; select: (id: LanguageStage) => void;
}) {
  const t = (ko: string, en: string) => locale === 'ko' ? ko : en;
  const [tab, setTab] = useState<Tab>('concept');
  const [answer, setAnswer] = useState(false);
  const [node, setNode] = useState(0);
  const index = languageStages.findIndex(item => item[0] === r.stage);
  const name = languageStages[index][locale === 'ko' ? 1 : 2];
  const reviewed = Boolean(r.evidence[r.stage]?.trim()) && r.reviewed[r.stage] === r.evidence[r.stage];
  const [confirmed, setConfirmed] = useState(reviewed);
  function keyboard(event: KeyboardEvent<HTMLButtonElement>, i: number) {
    const next = event.key === 'ArrowRight' ? (i + 1) % tabs.length : event.key === 'ArrowLeft' ? (i + tabs.length - 1) % tabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : -1;
    if (next >= 0) { event.preventDefault(); setTab(tabs[next][0]); document.getElementById(`tab-${tabs[next][0]}`)?.focus(); }
  }
  return <div className="learning-grid"><article className="learning-main track-lesson">
    <header className="learning-header"><span className="learning-kicker">{codeLanguages.find(item => item.id === language)!.name} · {index + 1} / 15</span><h1 tabIndex={-1}>{name}</h1><LessonText text={c.summary[locale]} /></header>
    <>{c.scope && <p className="learning-box" data-testid="chapter-scope">{c.scope[locale]}</p>}</><div className="curriculum-tabs" role="tablist" aria-label={t('수업 내용', 'Lesson content')}>{tabs.map(([id, ko, en], i) => <button className="learn-secondary" key={id} id={`tab-${id}`} role="tab" aria-selected={id === tab} aria-controls="curriculum-panel" tabIndex={id === tab ? 0 : -1} onClick={() => setTab(id)} onKeyDown={event => keyboard(event, i)}>{t(ko, en)}</button>)}</div>
    <section id="curriculum-panel" role="tabpanel" aria-labelledby={`tab-${tab}`} tabIndex={0}>
      {tab === 'concept' && <><h2>{t('선수 지식과 준비', 'Prerequisites and preparation')}</h2><LessonText text={c.prerequisites[locale]} /><h2>{t('먼저 알아둘 말', 'Plain-language glossary')}</h2><LessonText text={c.glossary[locale]} glossary />{c.concepts.map((part, i) => <section className="learning-box" key={i}><h2>{part.title[locale]}</h2><LessonText text={part.body[locale]} /></section>)}<h2>{t('필요한 이유 · 선택과 한계', 'Why it matters · choices and limits')}</h2><LessonText text={c.tradeoffs[locale]} /><h2>{t('활용 사례', 'Use cases')}</h2><LessonText text={c.useCase[locale]} />{c.sources && <><h2>{t('참고 자료', 'References')}</h2><ul>{c.sources.map(s => <li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.label[locale]} ↗</a></li>)}</ul></>}
      <label className="learning-checkbox-row"><input type="checkbox" checked={r.read.includes(r.stage)} onChange={e => update({ ...r, read: e.target.checked ? [...new Set([...r.read, r.stage])] : r.read.filter(id => id !== r.stage) })} /><span>{t('읽기 완료로 기록 (숙련과 별개)', 'Mark as read (separate from mastery)')}</span></label>{saved && r.read.includes(r.stage) && <p className="read-confirmation" role="status">{t("읽기 기록을 저장했습니다. 숙련 평가와는 별개입니다.", "Reading record saved; separate from mastery.")}</p>}</>}
      {tab === 'example' && <><h2>{t('환경 준비', 'Environment preparation')}</h2><LessonText text={c.preparation[locale]} /><pre><code>{c.preparationCode}</code></pre><h2>{t('실행 명령', 'Run commands')}</h2><pre><code>{c.run}</code></pre>{c.scope && <div className="learning-box"><LessonText text={c.scope[locale]} /></div>}{c.concepts.filter(s => s.code).map((s, i) => <section key={i}><h2>{s.title[locale]}</h2><pre><code>{s.code}</code></pre><h3>{t('예상 결과 · 실행 기록 아님', 'Expected result · not an execution record')}</h3><pre>{s.output[locale]}</pre></section>)}{c.exampleFiles && <ul>{c.exampleFiles.map(file => <li key={file}><code>{file}</code></li>)}</ul>}<details><summary>{t('격리 예제 검증 명령', 'Isolated example verification')}</summary><pre><code>{c.verification}</code></pre></details></>}
      {tab === 'flow' && <><p>{t('설명용 흐름입니다. 이 화면은 서버를 실행하거나 장애를 바꾸지 않습니다.', 'An explanatory flow. This page does not start servers or change faults.')}</p><div className="curriculum-flow">{c.flow.map((s, i) => <button key={i} className="learn-secondary" aria-pressed={node === i} onClick={() => setNode(i)}>{s.title[locale]}</button>)}</div><div className="learning-box"><LessonText text={c.flow[node].body[locale]} /></div><h2>{t('먼저 예측하기', 'Predict first')}</h2><LessonText text={c.prediction[locale]} /><label htmlFor="curriculum-prediction">{t('내 예측 · 메모', 'My prediction · notes')}</label><textarea id="curriculum-prediction" value={r.notes[r.stage] ?? ''} onChange={e => update({ ...r, notes: { ...r.notes, [r.stage]: e.target.value } })} /><button className="learn-secondary" aria-expanded={answer} onClick={() => setAnswer(!answer)}>{t('해설 보기/접기', 'Show/hide explanation')}</button>{answer && <div id="prediction-explanation"><LessonText text={c.answer[locale]} /></div>}</>}
      {tab === 'practice' && <><h2>{t('따라 해 보기', 'Guided practice')}</h2><LessonText text={c.guided[locale]} /><h2>{t('혼자 풀기', 'Independent practice')}</h2><LessonText text={c.exercise[locale]} /><details className="learning-disclosure"><summary>{t('힌트', 'Hint')}</summary><LessonText text={c.hint[locale]} /></details><details className="learning-disclosure"><summary>{t('풀이와 비교', 'Compare with a solution')}</summary><LessonText text={c.solution[locale]} /></details><h2>{t('확인 가능한 기준', 'Observable criteria')}</h2><LessonText text={c.criteria[locale]} /></>}
      {tab === 'troubleshoot' && <><h2>{t('오류 해결 순서', 'Troubleshooting sequence')}</h2><LessonText text={c.failure[locale]} /><p>{t('실제 입력, 예상 결과, 실제 결과, 확인한 원인과 재검증 결과를 기록하세요. 실행하지 않았다면 미실행이라고 적으세요.', 'Record the input, expected/actual results, checked cause and verification. State explicitly if you did not execute it.')}</p></>}
      {tab === 'check' && <><KnowledgeCheck language={language} stage={javaStage(r.stage)} /><h2>{t('내 실행·검증 기록', 'My execution and verification record')}</h2><LessonText text={c.criteria[locale]} /><label htmlFor="practice-evidence">{t('내 실행·검증 기록', 'My execution and verification record')}</label><textarea id="practice-evidence" value={r.evidence[r.stage] ?? ''} onChange={e => { setConfirmed(false); const next = { ...r, evidence: { ...r.evidence, [r.stage]: e.target.value }, reviewed: { ...r.reviewed } }; delete next.reviewed[r.stage]; update(next); }} /><label className="learning-checkbox-row"><input type="checkbox" checked={confirmed} onChange={e => { setConfirmed(e.target.checked); if (!e.target.checked) { const next = { ...r, reviewed: { ...r.reviewed } }; delete next.reviewed[r.stage]; update(next); } }} /><span>{t('통과 기준을 내 기록과 대조했습니다 (자기 확인)', 'I compared the criteria with my record (self-review)')}</span></label><button className="learn-primary" disabled={!confirmed || !r.evidence[r.stage]?.trim()} onClick={() => update({ ...r, reviewed: { ...r.reviewed, [r.stage]: r.evidence[r.stage] } })}>{t('자기 확인 기록 저장', 'Save self-review record')}</button><p className="practice-confirmation" role="status">{reviewed && saved ? t('자기 확인 기록을 저장했습니다. 자동 검증하지 않습니다. 숙련 인증은 아닙니다.', 'Self-review record saved; this is not automatic verification or certification.') : t('실행하지 않은 항목은 미실행으로 기록하세요.', 'Mark unrun items as unrun.')}</p></>}
    </section>
    <nav className="learning-next" aria-label={t('단계 이동', 'Stage navigation')}><button className="learn-secondary" disabled={index === 0} onClick={() => select(languageStages[index - 1][0])}>{t('이전 학습', 'Previous lesson')}</button><button className="learn-primary" disabled={index === 14} onClick={() => select(languageStages[index + 1][0])}>{t('다음 학습', 'Next lesson')}</button></nav>
  </article><aside className="learning-coach"><h2>{t('이번 단계의 목표', 'This stage’s goal')}</h2><LessonText text={c.criteria[locale]} /><details><summary>{t('학습 도움', 'Learning help')}</summary><LessonText text={c.hint[locale]} /></details><p>{t('읽기와 직접 실행은 별개입니다. 안내는 AI 대화가 아닙니다.', 'Reading and execution are separate. This guidance is not an AI chat.')}</p></aside></div>;
}
