import java.sql.*;
import java.util.*;
class Stage15Capstone {
  record Receipt(int orderId,int total) {}
  record Draft(String hypothesis,Set<String> evidenceIds) {}
  static Draft evaluate(Draft candidate,Set<String> knownIds) {
    if(candidate==null || candidate.hypothesis()==null || candidate.evidenceIds()==null || candidate.hypothesis().getBytes(java.nio.charset.StandardCharsets.UTF_8).length>512 || candidate.evidenceIds().isEmpty() || !knownIds.containsAll(candidate.evidenceIds())) {
      return new Draft("Insufficient validated evidence; inspect original observations",Set.of());
    }
    return candidate;
  }
  static Receipt order(Connection db,String user,String owner,String key,int quantity) throws SQLException {
    if(user==null || !user.equals(owner)) throw new SecurityException("owner required");
    if(quantity<1 || quantity>10) throw new IllegalArgumentException("quantity");
    try(PreparedStatement previous=db.prepareStatement("SELECT id,total,quantity FROM purchase WHERE owner=? AND idem_key=?")) {
      previous.setString(1,owner); previous.setString(2,key);
      try(ResultSet row=previous.executeQuery()) {
        if(row.next()) { if(row.getInt(3)!=quantity) throw new IllegalArgumentException("key conflict"); return new Receipt(row.getInt(1),row.getInt(2)); }
      }
    }
    db.setAutoCommit(false);
    try {
      try(PreparedStatement stock=db.prepareStatement("UPDATE product SET stock=stock-? WHERE id=1 AND stock>=?")) {
        stock.setInt(1,quantity); stock.setInt(2,quantity);
        if(stock.executeUpdate()!=1) throw new IllegalArgumentException("insufficient stock");
      }
      int total=Math.multiplyExact(1200,quantity);
      try(PreparedStatement create=db.prepareStatement("INSERT INTO purchase(owner,idem_key,quantity,total) VALUES(?,?,?,?)",Statement.RETURN_GENERATED_KEYS)) {
        create.setString(1,owner); create.setString(2,key); create.setInt(3,quantity); create.setInt(4,total); create.executeUpdate();
        try(ResultSet keys=create.getGeneratedKeys()) {
          keys.next(); int id=keys.getInt(1);
          try(PreparedStatement outbox=db.prepareStatement("INSERT INTO outbox VALUES(?)")) { outbox.setInt(1,id); outbox.executeUpdate(); }
          db.commit(); return new Receipt(id,total);
        }
      }
    } catch(SQLException | RuntimeException error) { db.rollback(); throw error; }
    finally { db.setAutoCommit(true); }
  }
  public static void main(String[] args) throws Exception {
    try(Connection db=DriverManager.getConnection("jdbc:h2:mem:capstone_lesson")) {
      Statement sql=db.createStatement();
      sql.execute("CREATE TABLE product(id INT PRIMARY KEY,stock INT CHECK(stock>=0))"); sql.execute("INSERT INTO product VALUES(1,3)");
      sql.execute("CREATE TABLE purchase(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,owner VARCHAR(40),idem_key VARCHAR(40),quantity INT,total INT,UNIQUE(owner,idem_key))");
      sql.execute("CREATE TABLE outbox(purchase_id INT PRIMARY KEY REFERENCES purchase(id))");
      Receipt first=order(db,"alice","alice","k1",2);
      if(first.total()!=2400 || !first.equals(order(db,"alice","alice","k1",2))) throw new AssertionError("retry");
      try { order(db,"bob","alice","k2",1); throw new AssertionError("authorization"); } catch(SecurityException expected) { }
      try { order(db,"alice","alice","k1",1); throw new AssertionError("key conflict"); } catch(IllegalArgumentException expected) { }
      try { order(db,"alice","alice","k2",2); throw new AssertionError("stock"); } catch(IllegalArgumentException expected) { }
      try(ResultSet row=sql.executeQuery("SELECT stock FROM product WHERE id=1")) { row.next(); if(row.getInt(1)!=1) throw new AssertionError("rollback stock"); }
      for(String table:List.of("purchase","outbox")) try(ResultSet row=sql.executeQuery("SELECT COUNT(*) FROM "+table)) { row.next(); if(row.getInt(1)!=1) throw new AssertionError("transaction invariant"); }
    }
    Draft invalid=new Draft("Cause is proven",Set.of("invented-id"));
    if(evaluate(invalid,Set.of("e1")).equals(invalid)) throw new AssertionError("fabricated citation");
    if(!evaluate(new Draft("가".repeat(200),Set.of("e1")),Set.of("e1")).evidenceIds().isEmpty()) throw new AssertionError("UTF-8 byte bound");
    if(!evaluate(null,Set.of()).evidenceIds().isEmpty()) throw new AssertionError("null fallback");
    Draft valid=new Draft("A hypothesis to verify",Set.of("e1"));
    if(!evaluate(valid,Set.of("e1")).equals(valid)) throw new AssertionError("valid citation");
    System.out.println("PASS capstone H2: authorization, retry, key conflict, stock rollback, one order=one outbox");
    System.out.println("PASS optional report-validation MODEL: invented evidence rejected; no LLM call or provider evaluation");
    System.out.println("Sequential reference only: concurrent unique-key retry recovery and production auth require further implementation.");
  }
}
