import type { Copy, Guide } from "./technology-guides";

type Pair = [string, string];
type Story = [Pair, Pair, Pair, Pair, Pair, Pair, Pair, Pair, Pair, Pair, Pair, Pair];
const copy = ([ko, en]: Pair): Copy => ({ ko, en });
function make(id: string, name: string, group: Guide["group"], _stage: string | undefined, mode: Guide["mode"], story: Story, example: string, source: string): Guide {
  const [problem, oldWay, purpose, boundary, flow, exampleNote, inLab, observe, diagnose, alternatives, guided, independent] = story.map(copy) as [Copy, Copy, Copy, Copy, Copy, Copy, Copy, Copy, Copy, Copy, Copy, Copy];
  return { id, name, group, mode, problem, oldWay, purpose, boundary, flow, example, exampleNote, inLab, observe, diagnose, alternatives, guided, independent, source };
}
export const additionalGuides: Guide[] = [
  make("java-spring", "Java · Spring Boot", "core", "spring", "core", [
    ["HTTP 요청마다 검증·오류·업무·DB 연결을 직접 묶으면 코드가 반복됩니다.", "Hand-wiring validation, errors, business rules and DB access on every route becomes repetitive."],
    ["Java 표준 도구로 작은 서버를 만들 수 있지만 여러 서비스는 같은 요청·설정·저장 경계가 필요합니다.", "Java can host a small server, but multiple services need consistent request, configuration and persistence boundaries."],
    ["Java는 JVM 언어, Spring Boot는 Java 앱을 구성·시작하는 프레임워크입니다. Controller는 HTTP, Service는 업무 규칙, 저장 계층은 DB를 맡습니다.", "Java is a JVM language; Spring Boot configures and starts the app. Controllers handle HTTP, services business rules and persistence components the DB."],
    ["Spring이 잘못된 업무 규칙이나 의존 서비스 장애를 고치지 않습니다. 이 로컬 앱에는 애플리케이션 인증이 없습니다.", "Spring cannot fix incorrect business rules or failed dependencies. This local app has no application authentication."],
    ["브라우저 → control-plane Controller → 사고·증거 Service → MySQL/Redis 또는 demo-api → JSON. 주문 경로는 demo-api → MySQL order/outbox → Kafka → worker입니다.", "Browser → control-plane Controller → incident/evidence service → MySQL/Redis or demo-api → JSON. The order path continues through demo-api → MySQL order/outbox → Kafka → worker."],
    ["Controller 경계만 보이는 설명용 코드입니다. Service와 실행 프로젝트가 없어 단독 실행할 수 없습니다.", "Illustrative controller fragment; without a service and project it cannot run alone."],
    ["control-plane, demo-api, demo-worker는 별도 Spring Boot 서비스입니다. libs/common은 wire record·계측·안전한 오류를 공유합니다.", "control-plane, demo-api and demo-worker are separate Spring Boot services. libs/common shares wire records, telemetry and safe errors."],
    ["실험실에서 요청 상태·서비스별 증거·correlation ID를 비교해 어느 소유자에서 흐름이 멈췄는지 봅니다.", "Compare HTTP status, per-service evidence and correlation ID to locate the stopped owner."],
    ["4xx 입력 문제, 5xx 서비스/의존성 문제, 시작 실패의 설정/포트/DB 준비를 구분합니다.", "Separate 4xx input, 5xx service/dependency and startup configuration/port/DB readiness."],
    ["한두 경로의 작은 앱에는 단일 파일이 충분할 수 있습니다. Spring은 구조와 함께 설정·의존성 비용도 더합니다.", "A tiny one-route app may need only one file. Spring adds setup and dependencies along with structure."],
    ["4단계 Controller→Service를 찾아 실제 demo-api 주문 경계와 다른 점을 적으세요.", "Locate stage-4 Controller→Service and compare it with demo-api's order boundary."],
    ["상품 없음과 DB 연결 실패를 어느 계층에서 어떤 HTTP 응답으로 처리할지 설계하세요.", "Design layers and HTTP responses for a missing product and a DB outage."],
  ], "@GetMapping(\"/api/products/{id}\")\nProduct get(@PathVariable long id) {\n  return productService.find(id);\n}", "https://docs.spring.io/spring-boot/reference/"),
  make("services", "control-plane · API · worker · outbox", "core", "messaging", "core", [
    ["사고 통제와 주문 처리가 한 경계에 섞이면 실패 책임과 접수/완료 의미가 흐려집니다.", "Mixing incident control with order processing blurs ownership and accepted-versus-complete status."],
    ["한 프로세스에서 동기 처리할 수 있지만 느린 후속 작업이 HTTP 응답을 붙잡고 실패가 연쇄됩니다.", "Synchronous work in one process is possible, but slow follow-up holds HTTP and propagates failure."],
    ["control-plane은 세션·장애·증거·RCA, demo-api는 상품·주문·outbox, demo-worker는 fulfillment·중복 방지를 소유합니다. outbox는 주문과 발행 의도를 한 DB 트랜잭션에 묶습니다.", "control-plane owns sessions/faults/evidence/RCA; demo-api owns catalog/orders/outbox; demo-worker owns fulfillment/deduplication. The outbox commits order and publication intent together."],
    ["서비스 분리는 분산 트랜잭션이 아닙니다. HTTP 201은 접수이지 fulfillment 완료가 아니며 worker는 결제·배송을 하지 않습니다.", "Service separation is not a distributed transaction. HTTP 201 means accepted, not fulfilled; the worker does not charge or ship."],
    ["브라우저는 control-plane을 이용합니다. 부하 요청은 demo-api에 주문 → MySQL order+outbox → relay → Kafka → worker → 별도 MySQL 처리 결과로 이동합니다.", "Browser uses control-plane. Load requests flow to demo-api order → MySQL order+outbox → relay → Kafka → worker → separate MySQL result."],
    ["저장소의 계약을 축약한 도식이며 실행 명령이나 측정 결과가 아닙니다.", "A compact diagram of the repository contract, not a runnable command or measurement."],
    ["세 Spring 모듈에 소유 schema가 있습니다. 같은 Idempotency-Key·payload면 replay, 다른 payload면 409이며 relay는 완료 표시 실패 시 재발행할 수 있습니다.", "Three Spring modules own separate schemas. Same Idempotency-Key/payload replays; changed payload is 409, and relay may republish after a failed completion mark."],
    ["주문 상태, outbox pending, Kafka lag, worker processed/duplicate를 서로 다른 단계의 신호로 읽습니다.", "Treat order state, pending outbox, Kafka lag and worker processed/duplicate as different stage signals."],
    ["접수 실패는 API/DB, 접수 뒤 outbox 대기는 relay/broker, 발행 뒤 효과 부재는 worker retry/DLQ, 중복 효과는 처리 ID/DB 제약을 봅니다.", "Acceptance failure → API/DB; pending outbox → relay/broker; no effect after publication → worker retry/DLQ; duplicate effect → processed ID/DB constraints."],
    ["작은 기능은 한 서비스의 동기 작업이 더 단순할 수 있습니다. 분리는 네트워크·계약·운영 비용을 만듭니다.", "A small feature may be simpler synchronously in one service. Separation adds network, contract and operations costs."],
    ["ARCHITECTURE.md의 201 이전과 이후 경계를 표시하세요.", "Mark boundaries before and after HTTP 201 in ARCHITECTURE.md."],
    ["DB 커밋 뒤 Kafka 장애와 worker 커밋 뒤 offset 장애에서 사용자 상태·재시도·중복 효과를 예측하세요.", "Predict visible status, retries and duplicate effects for broker failure after DB commit and offset failure after worker commit."],
  ], "HTTP 201 = order accepted\nAPI DB: order + outbox (one commit)\nKafka delivery: may repeat\nWorker DB: processed_event + fulfillment (one commit)", "https://github.com/NIGHTPURI/incident-lens/blob/main/ARCHITECTURE.md"),
  make("mysql", "MySQL", "data", "persistence", "core", [
    ["주문을 메모리에만 두면 재시작에 사라지고 중복 키·동시 수정 규칙을 직접 구현해야 합니다.", "Memory-only orders disappear on restart and need custom duplicate-key and concurrency rules."],
    ["파일은 남지만 여러 요청의 관계·제약·원자적 다중 쓰기를 손으로 구현해야 합니다.", "Files persist, but relationships, constraints and atomic multi-write operations need manual work."],
    ["MySQL은 관계형 DB입니다. 테이블·키·트랜잭션으로 함께 성공/실패해야 할 주문과 outbox를 관리합니다.", "MySQL is a relational DB; tables, keys and transactions coordinate order and outbox writes that must succeed or fail together."],
    ["DB 트랜잭션은 Kafka나 외부 HTTP를 되돌리지 않습니다. 독립 H2 수업 통과는 MySQL 잠금·성능 보증이 아닙니다.", "A DB transaction does not roll back Kafka or HTTP. Passing standalone H2 lessons does not verify MySQL locks or performance."],
    ["demo-api가 주문 키 검증 → MySQL order+outbox 한 커밋 → relay가 미발행 행 claim → worker는 별도 schema에 처리 ID·결과 저장.", "demo-api validates order key → one MySQL order+outbox commit → relay claims pending row → worker writes processed ID and result to its own schema."],
    ["컬럼을 생략한 SQL 도식입니다. 원본 schema의 실행 가능한 마이그레이션이 아닙니다.", "SQL sketch with omitted columns, not a runnable migration for the actual schema."],
    ["로컬 MySQL 하나가 control_plane·demo_api·demo_worker schema를 호스팅합니다. Flyway가 DDL을, unique key가 idempotency/중복 효과를 보호합니다.", "One local MySQL hosts control_plane, demo_api and demo_worker schemas. Flyway owns DDL; unique keys guard idempotency and duplicate effects."],
    ["DB 지연 실험에서는 HTTP p95, catalog DB-operation 수/p95, 오류를 함께 봅니다. outbox pending은 발행 전 대기를 나타냅니다.", "For DB degradation, inspect HTTP p95, catalog DB-operation count/p95 and errors. Pending outbox indicates pre-publication backlog."],
    ["접속 실패는 readiness/설정, 느린 조회는 실제 SQL·인덱스·계획, 중복은 unique key와 트랜잭션을 확인합니다.", "For connection failures check readiness/config; for slow reads actual SQL/index/plans; for duplicates unique keys and transactions."],
    ["작은 정적 데이터는 파일이나 SQLite도 충분할 수 있습니다. MySQL은 서버·마이그레이션·백업 비용이 듭니다.", "Small static data may fit a file or SQLite. MySQL adds server, migration and backup costs."],
    ["5단계 H2 예제와 세 MySQL schema를 비교해 검증 경계를 적으세요.", "Compare stage-5 H2 and the three MySQL schemas, noting verification limits."],
    ["동시 주문 두 개가 같은 키를 쓸 때 같은 payload/다른 payload의 DB·HTTP 결과를 설계하세요.", "Design DB and HTTP outcomes when two concurrent orders share a key with identical versus different payloads."],
  ], "BEGIN;\nINSERT INTO purchase_order (...);\nINSERT INTO outbox_event (...);\nCOMMIT;\n-- one failure before COMMIT means rollback", "https://dev.mysql.com/doc/refman/8.4/en/innodb-transaction-model.html"),
  make("docker", "Docker · Compose", "core", "operations", "core", [
    ["서비스마다 Java·DB·브로커 버전과 포트가 다르면 실행 절차를 다른 PC에서 재현하기 어렵습니다.", "Different Java/DB/broker versions and ports make a setup hard to reproduce on another PC."],
    ["직접 설치·시작해도 되지만 의존성 준비 순서, 데이터 디렉터리, 설정 관리가 늘어납니다.", "Manual startup works but increases dependency-order, data-directory and configuration work."],
    ["Docker는 이미지를 컨테이너로 실행하고 Compose는 서비스·연결·볼륨·health·선택 프로필을 선언합니다.", "Docker runs images in containers; Compose declares services, networks, volumes, health and optional profiles."],
    ["컨테이너가 보안·백업·성능을 자동 보장하지 않습니다. 이 안내는 이미지 다운로드나 앱 재시작을 하지 않습니다.", "Containers do not automatically guarantee security, backup or performance. This guide downloads no image and restarts no app."],
    ["Compose 기본은 MySQL/Redis/Kafka → 세 Spring 서비스 → web입니다. 관측 프로필을 선택하면 관측 서비스가 추가됩니다.", "Core Compose flows through MySQL/Redis/Kafka → three Spring services → web. Choosing observability adds telemetry services."],
    ["원본 Compose에서 일부만 뽑은 설명용 YAML입니다. 실행 명령이 아닙니다.", "Reduced illustrative YAML from Compose; not a runnable command."],
    ["기본 프로필 7서비스, loadtest의 k6, observability의 Prometheus/Grafana/Loki/Tempo/Collector로 구분합니다. 로컬 공개 포트는 loopback입니다.", "Seven core services, k6 in loadtest and Prometheus/Grafana/Loki/Tempo/Collector in observability. Published local ports bind loopback."],
    ["실험 전 서비스 연결과 readiness를 보되 container healthy가 주문 성공을 대신하지 않음을 기억하세요.", "Check service connectivity/readiness before an experiment; container healthy does not prove order success."],
    ["시작 실패는 의존 health, 포트 충돌, 메모리, 볼륨 공간, 설정을 분리합니다.", "Separate dependency health, port conflicts, memory, volume space and configuration on startup failure."],
    ["한 파일 앱은 직접 실행이 단순합니다. Compose는 운영 배포·백업 플랫폼을 대신하지 않습니다.", "Direct launch is simpler for a one-file app; Compose is not a deployment or backup platform."],
    ["Compose의 기본·loadtest·observability 서비스와 MySQL 볼륨을 찾아보세요.", "Classify core/loadtest/observability services and locate the MySQL volume."],
    ["worker만 준비되지 않은 상황에서 주문 접수와 후속 처리의 상태를 각각 예측하세요.", "Predict accepted-order and follow-up status if only worker is unready."],
  ], "demo-api:\n  depends_on:\n    mysql: { condition: service_healthy }\n# reduced sketch; see docker-compose.yml", "https://docs.docker.com/compose/"),
  make("k6", "k6", "observe", "observability", "optional", [
    ["요청 한 번의 빠른 응답만으로 반복 부하의 지연·오류를 판단할 수 없습니다.", "One fast request says little about latency and errors under repeated load."],
    ["브라우저 새로고침은 요청 수·가상 사용자·기간을 일정하게 재현하지 못합니다.", "Browser refreshes do not reproduce virtual users, request rate and duration consistently."],
    ["k6는 지정한 HTTP workload를 보내고 수·지연 분포·오류를 요약하는 부하 생성 도구입니다.", "k6 generates a specified HTTP workload and summarizes counts, latency distribution and errors."],
    ["k6가 원인이나 서버 내부 시간을 자동 설명하지 않습니다. 이 앱의 요약은 제출된 측정값을 검증하지만 계측 결과의 출처를 암호학적으로 증명하지 않습니다.", "k6 does not explain root cause or server internals. This app validates submitted summaries but does not cryptographically attest their provenance."],
    ["운영자가 터미널에서 동일 VU·기간·상품/주문 요청을 BEFORE/AFTER에 실행 → control-plane이 범위와 요약을 검증·저장 → 증거와 비교합니다.", "An operator runs the same VUs, duration and catalog/order mix in a terminal for BEFORE/AFTER → control-plane validates/stores summary → compare with evidence."],
    ["설명용 명령입니다. 이 화면은 부하를 만들거나 실험 결과를 재생성하지 않습니다.", "Illustrative command; this page neither creates load nor regenerates experiment results."],
    ["Compose의 loadtest 프로필에 별도 k6가 있고 loadtest/에 baseline, cache-stampede, kafka-backlog, latency-incident 스크립트가 있습니다. 브라우저에서는 k6가 실행되지 않습니다.", "The loadtest profile has k6; loadtest/ includes baseline, cache-stampede, kafka-backlog and latency-incident scripts. The browser never runs k6."],
    ["BEFORE/AFTER의 VU·기간·요청 혼합·성공률·p50/p95/p99·throughput을 먼저 맞춰 봅니다. 공유 lag는 사고별 숫자가 아닙니다.", "Compare VUs, duration, request mix, success rate, p50/p95/p99 and throughput across BEFORE/AFTER. Shared lag is not per-incident."],
    ["표본 수가 적거나 오류가 많으면 percentile 해석이 흔들립니다. 두 단계의 workload 설정과 측정 단위, 서버 증거 범위를 확인합니다.", "Few samples or many errors weaken percentile interpretation. Check identical workload settings, units and server-evidence scope."],
    ["작은 API 기능 확인은 수동 호출/테스트로 충분합니다. 부하 생성은 실제 컴퓨터에 부담을 주므로 이 안내가 자동 실행하지 않습니다.", "A manual request/test suffices for a simple API check. Load generation consumes resources, so this guide never runs it automatically."],
    ["README의 BEFORE/AFTER 절차에서 동일하게 유지할 변수 세 가지를 적으세요.", "Find three settings that must remain identical across BEFORE/AFTER in the README workflow."],
    ["p95 상승과 오류 증가가 동시에 보일 때 결론 전에 필요한 workload·서버 증거를 설계하세요.", "When p95 and errors both rise, design the workload and server evidence needed before a conclusion."],
  ], "docker compose --profile loadtest run --rm k6 run /scripts/baseline.js\n# illustrative; do not run without a controlled lab session", "https://grafana.com/docs/k6/latest/"),
  make("otel", "OpenTelemetry · Collector", "observe", "observability", "optional", [
    ["서비스를 지나는 한 요청이 어디서 시간을 쓰고 어떤 로그를 남겼는지 숫자 하나로는 알기 어렵습니다.", "A single metric cannot show where one request spent time across services or its related logs."],
    ["서비스마다 별도 로그를 읽으면 요청 ID와 시간대 연결을 수동으로 맞춰야 합니다.", "Separate logs require manual request-ID and time-window correlation."],
    ["OpenTelemetry Java agent는 HTTP/JDBC/Redis/Kafka 경계를 계측합니다. Collector는 받은 trace/log를 처리해 Tempo/Loki로 전달합니다.", "The OpenTelemetry Java agent instruments HTTP/JDBC/Redis/Kafka. Collector processes received traces/logs and exports them to Tempo/Loki."],
    ["Collector는 이 Compose에서 metric 저장소가 아닙니다. 지표는 Prometheus가 직접 스크레이프합니다. agent가 꺼져 있으면 trace 참조가 없을 수 있습니다.", "Collector is not this Compose's metric store. Prometheus scrapes metrics directly. With agent disabled, trace references may be absent."],
    ["Java 서비스/agent → OTLP HTTP → Collector memory limiter/batch → trace는 Tempo, log는 Loki. outbox relay는 저장된 W3C 문맥을 다시 이어 Kafka 소비자로 전파합니다.", "Java service/agent → OTLP HTTP → Collector memory limiter/batch → traces to Tempo, logs to Loki. Outbox relay restores stored W3C context before Kafka publication."],
    ["구성 경로의 설명 도식입니다. 이 화면에서 trace를 생성하지 않습니다.", "Illustrative configuration path. This page generates no trace."],
    ["observability 프로필에 Collector가 있고 OTEL_SDK_DISABLED 기본값은 true입니다. Java agent와 환경 설정이 있어야 자동 trace가 생깁니다.", "Collector is in observability profile and OTEL_SDK_DISABLED defaults to true. The Java agent and configuration must be enabled for automatic traces."],
    ["실험 증거의 trace ID가 있을 때 Tempo에서 흐름을 따라가고, 같은 correlation ID의 Loki 로그와 비교합니다. 누락은 결측으로 둡니다.", "When evidence includes a trace ID, follow it in Tempo and compare Loki logs with the correlation ID. Treat absence as missing data."],
    ["span이 비면 agent 사용 여부, OTLP endpoint, Collector pipeline, exporter와 Tempo 연결을 차례로 봅니다. 로그만 오는지 trace만 오는지도 분리합니다.", "For missing spans inspect agent enablement, OTLP endpoint, Collector pipeline, exporter and Tempo connection. Separate log-only from trace-only failure."],
    ["작은 단일 서비스는 명확한 로그와 직접 증거로 시작할 수 있습니다. 계측은 저장량·비용·민감 정보·sampling 판단을 추가합니다.", "A small single service can begin with clear logs/direct evidence. Instrumentation adds storage, cost, sensitive-data and sampling concerns."],
    ["HTTP→DB→outbox→Kafka→worker에서 자동 agent와 수동 문맥 복원 경계를 각각 표시하세요.", "Mark automatic agent and explicit context-restoration boundaries across HTTP→DB→outbox→Kafka→worker."],
    ["trace ID가 없다면 서비스가 정상이라고 해석할 수 없는 이유와 확인 순서를 설명하세요.", "Explain why absent trace ID does not imply a healthy service and list your checks."],
  ], "Java agent → OTLP :4318 → Collector\nCollector traces → Tempo\nCollector logs → Loki\nPrometheus scrapes metrics separately", "https://opentelemetry.io/docs/collector/"),
  make("loki", "Loki", "observe", "observability", "optional", [
    ["오류가 난 요청을 aggregate p95만으로는 어떤 메시지·경계에서 실패했는지 설명하기 어렵습니다.", "Aggregate p95 cannot show the message or boundary for one failed request."],
    ["서로 다른 컨테이너 로그를 수동으로 뒤지면 시간·서비스·correlation ID를 놓치기 쉽습니다.", "Manually searching container logs can miss time, service and correlation ID."],
    ["Loki는 이 관측 구성에서 구조화된 로그를 보관·질의하고 Grafana Explore가 이를 보여줍니다.", "Loki stores and queries structured logs in this observability setup; Grafana Explore presents them."],
    ["로그는 평균 지연 수치나 전체 trace 경로의 대체물이 아닙니다. 앱은 요청 본문·자격 증명·LLM 응답 원문을 기록하지 않도록 설계되었습니다.", "Logs do not replace latency aggregates or complete traces. The app avoids recording request bodies, credentials and raw LLM responses."],
    ["서비스 JSON 로그/agent → OTLP → Collector → Loki → Grafana 질의. correlationId, incidentId, phase와 서비스 이름으로 해당 범위를 좁힙니다.", "Service JSON logs/agent → OTLP → Collector → Loki → Grafana query. Narrow by correlationId, incidentId, phase and service."],
    ["질의 과정의 설명일 뿐 실제 로그 줄이나 Live 결과가 아닙니다.", "Illustrative query path, not a real log line or live result."],
    ["infra/loki 설정과 observability 프로필에 있습니다. 기본 앱 실행에는 필요하지 않으며 직접 사고 증거가 별도로 있습니다.", "Configured under infra/loki and the observability profile. Core app operation does not require it; direct incident evidence exists separately."],
    ["사고 ID와 시간 범위를 맞추고 오류의 첫 발생·다음 서비스 경계를 비교합니다. 로그가 없으면 Collector 상태와 agent 설정도 봅니다.", "Align incident ID/time and compare first error with the next service boundary. Missing logs also require Collector/agent checks."],
    ["예상 로그가 없으면 앱 출력 → agent OTLP → Collector log pipeline → Loki ingest → Grafana 필터를 순서대로 확인합니다.", "For missing logs inspect app output → agent OTLP → Collector log pipeline → Loki ingest → Grafana filter."],
    ["짧은 실습은 로컬 로그 읽기로 충분할 수 있습니다. 중앙 로그는 저장·보존·개인정보·label 설계 비용이 있습니다.", "A short exercise may only need local logs. Central logs add storage, retention, privacy and label-design costs."],
    ["동일 correlation ID의 API·worker 로그를 찾는 경로와 발견되지 않을 때의 검사를 적으세요.", "Write how to find API and worker logs for one correlation ID and what to check if absent."],
    ["p95만 높고 오류 로그가 없는 상황의 가능한 원인 두 가지와 검증 방법을 제안하세요.", "Propose two explanations and checks for high p95 without error logs."],
  ], "app JSON log → OTel Collector logs pipeline → Loki\nGrafana Explore → service + correlationId + time", "https://grafana.com/docs/loki/latest/"),
  make("tempo", "Tempo", "observe", "observability", "optional", [
    ["마이크로서비스의 한 요청이 어느 호출에서 늦었는지 집계 지표만으로 분리하기 어렵습니다.", "Aggregate metrics cannot locate the slow hop of one cross-service request."],
    ["서버마다 시각을 맞춰 로그를 읽을 수 있지만 부모·자식 호출 관계는 명시적으로 남기기 어렵습니다.", "You can align timestamps in logs, but parent-child call relationships are harder to reconstruct."],
    ["Tempo는 trace/span을 저장하고 Grafana에서 한 요청의 경로를 탐색하도록 합니다.", "Tempo stores traces/spans for Grafana exploration of one request's path."],
    ["trace 한 개는 전체 트래픽 대표값이 아닙니다. agent가 꺼져 있거나 span이 누락되면 경로가 불완전할 수 있습니다.", "One trace is not a traffic distribution. Disabled agents or missing spans leave an incomplete path."],
    ["Java agent span → Collector traces pipeline → Tempo → Grafana trace lookup. outbox에 저장한 traceparent를 relay가 복원해 비동기 경계를 잇습니다.", "Java agent spans → Collector traces pipeline → Tempo → Grafana lookup. Relay restores traceparent stored in outbox to bridge the asynchronous step."],
    ["설명용 span 순서이며 관측된 실제 trace가 아닙니다.", "Illustrative span order, not an observed trace."],
    ["infra/tempo와 observability 프로필에서만 사용합니다. 실험실 증거에는 trace ID가 있을 때 참조만 남고, agent 부재 시 비어 있을 수 있습니다.", "Used in infra/tempo and observability profile. Incident evidence may carry a trace ID; it can be absent without the agent."],
    ["HTTP→JDBC→Kafka→worker span의 시간과 부모 관계를 확인하고 관련 로그·metric의 시간대를 맞춥니다.", "Inspect timing and parent relationships across HTTP→JDBC→Kafka→worker spans, aligning related logs and metrics."],
    ["trace가 없으면 agent/collector/Tempo 경계를, 끊기면 outbox W3C 문맥 복원을 확인합니다.", "For no trace inspect agent/Collector/Tempo; for a broken path inspect outbox W3C context restoration."],
    ["단일 서비스와 분명한 로그면 trace 저장이 과할 수 있습니다. 샘플링·보존·저장 비용과 식별자 노출을 따져야 합니다.", "For one service with clear logs, trace storage may be excessive. Consider sampling, retention, storage and identifier exposure."],
    ["outbox 이전과 이후 중 수동 문맥 복원이 필요한 지점을 찾으세요.", "Find where explicit context restoration is needed around the outbox."],
    ["worker span만 없다면 어떤 세 경계를 확인할지 순서를 적으세요.", "Order three checks when only the worker span is absent."],
  ], "HTTP span → DB span → outbox\nrestore traceparent → Kafka span → worker span\n# conceptual, not a captured trace", "https://grafana.com/docs/tempo/latest/"),
  make("react-vite", "React · Vite · Nginx", "tools", "tools", "core", [
    ["사고와 근거를 긴 명령어만으로 탐색하면 실험 상태와 측정 구간 차이를 놓치기 쉽습니다.", "Command-line output alone can make incident state, evidence and measurement windows harder to navigate."],
    ["정적 HTML로도 표시할 수 있지만 한영·테마·OS 준비안과 비동기 API 상태를 화면에 동기화해야 합니다.", "Static HTML can display text, but locale, theme, OS plans and asynchronous API state need UI updates."],
    ["React는 화면 상태에 따라 컴포넌트를 렌더링합니다. Vite는 개발·빌드 도구이고 Nginx는 빌드된 파일을 제공하며 /api를 control-plane으로 프록시합니다. 둘 다 주문 서버가 아닙니다.", "React renders components from UI state. Vite is a dev/build tool; Nginx serves built files and proxies /api to control-plane. Neither is the order backend."],
    ["화면 성공 알림은 서버의 최종 작업 완료를 자동 보장하지 않습니다. 화면 언어와 OS 준비안 선택은 Java/Spring 실험 백엔드를 바꾸지 않습니다.", "A UI success notice does not prove final server work. UI locale and OS plans do not change the Java/Spring experiment backend."],
    ["브라우저 React → /api 프록시 → control-plane → demo-api/worker·증거. 개발 Vite 미리보기는 API를 기존 로컬 서비스에 프록시합니다.", "Browser React → /api proxy → control-plane → demo-api/worker/evidence. The Vite preview proxies API to the existing local service."],
    ["화면/API 경로 설명이며 새로운 요청을 실제로 보내지 않습니다.", "A UI/API path sketch; this page does not send a new experiment request."],
    ["apps/web의 홈·자유실험실·근거·비교 화면이 React입니다. Vite는 개발 미리보기, web 컨테이너의 Nginx는 정적 파일 제공·/api 프록시를 맡습니다.", "apps/web uses React for home, free lab, evidence and comparison. Vite serves development preview; web-container Nginx serves static files and proxies /api."],
    ["화면 알림, 선택한 세션/사고 ID, 실제 evidence 응답의 범위를 비교하세요. 늦은 비동기 응답은 다른 화면 상태에 영향을 줄 수 있습니다.", "Compare UI notice, selected session/incident ID and actual evidence scope. Late async responses can affect another screen's state."],
    ["화면이 비면 브라우저 오류 → Vite/Nginx 프록시 → control-plane 응답을 확인합니다. 성공 알림이 남으면 알림 소유 범위와 늦은 응답 경계를 봅니다.", "For a blank UI inspect browser errors → Vite/Nginx proxy → control-plane response. For a lingering success notice inspect notice ownership and late responses."],
    ["간단한 정보 페이지는 정적 HTML로 충분합니다. React/Vite는 상태·빌드·의존성 비용을 추가합니다.", "A simple info page may only need static HTML. React/Vite add state, build and dependency costs."],
    ["화면 한영 선택이 서버 근거의 원문을 변경하지 않는 이유를 요청 경로에서 확인하세요.", "Trace why switching the UI locale does not alter raw server evidence."],
    ["세션 A 요청이 늦게 끝난 뒤 세션 B 화면을 보고 있다면 어떤 데이터·알림을 버려야 할지 설계하세요.", "Design which data/notices to discard if session A finishes late while session B is selected."],
  ], "React UI → /api proxy → control-plane\nUI locale ≠ demo-api runtime", "https://react.dev/learn"),
  make("rca", "RCA · optional LLM provider", "tools", "observability", "optional", [
    ["지표 변화만 보고 곧바로 하나의 장애 원인을 확정하면 근거가 빠진 보고서가 됩니다.", "Jumping from a metric change to one root cause can produce an unsupported report."],
    ["사람이 증거를 읽고 가설을 쓸 수 있습니다. 반복 보고를 돕는 모델도 가능하지만 관측되지 않은 사실을 채울 위험이 있습니다.", "A person can read evidence and write hypotheses. A model can help draft, but may invent unobserved facts."],
    ["control-plane은 저장된 사고 증거를 근거로 RCA 가설·인용을 만들고 검증합니다. 외부 LLM은 설정할 때만 쓰는 선택 경로입니다.", "control-plane builds and validates evidence-cited RCA hypotheses. An external LLM is an optional configured path."],
    ["LLM 답변은 측정값·원인 확정이 아닙니다. 제공자 호출 없이 동작하는 경로가 있고, 기본 가이드가 유료 호출을 만들지 않습니다.", "An LLM answer is neither a measurement nor proof of cause. A path works without provider calls; this guide triggers no paid call."],
    ["실험 증거 저장 → 최신 BEFORE 증거 선택 → 후보 가설과 citation 생성/검증 → 보고서. AFTER는 동일 실험 조건 비교용이며 이전 보고서의 근거를 조용히 바꾸지 않습니다.", "Persist evidence → select newest BEFORE evidence → create/validate hypotheses with citations → report. AFTER is for comparison and does not silently rewrite an older report's citations."],
    ["가설 구조의 설명 예시이며 실제 모델 응답이나 보고서가 아닙니다.", "Illustrative hypothesis structure, not an actual model response or report."],
    ["RCA_BASE_URL/API key/model이 설정된 경우 제공자 경로를 사용할 수 있습니다. 앱은 빈 트래픽 증거에 양의 확신도를 부여하지 않도록 검증합니다.", "A configured RCA_BASE_URL/API key/model can enable the provider path. The app rejects positive confidence without observed traffic and a cited symptom."],
    ["보고서의 모든 인용이 저장된 증거로 이어지는지, 범위·시간·서비스와 경쟁 가설이 맞는지 확인합니다.", "Check every citation against stored evidence and compare scope, time, service and competing hypotheses."],
    ["근거가 비면 수집 범위·시각·트래픽 존재를 먼저 확인합니다. 모델 문장만 반복하지 말고 각 가설이 설명하지 못하는 증거를 찾습니다.", "If evidence is absent inspect scope/time/traffic first. Seek evidence each hypothesis fails to explain rather than repeating model prose."],
    ["작은 사건은 수동 메모가 더 명확할 수 있습니다. 제공자 경로는 비용·지연·개인정보·출력 검증 책임이 늘어납니다.", "For a small incident, manual notes may be clearer. Provider use adds cost, latency, privacy and output-validation obligations."],
    ["저장된 RCA 예시에서 주장 하나와 그 인용의 서비스·시간·수치를 대조하세요.", "For one stored RCA claim, compare its citation's service, time and measurement."],
    ["캐시 적중률 저하와 DB p95 상승만 있다면 원인 확정 없이 가능한 가설 두 개와 필요한 추가 증거를 적으세요.", "With only lower cache hit rate and higher DB p95, write two competing hypotheses and missing evidence without declaring a cause."],
  ], "hypothesis → cited evidence IDs → validation\nNo traffic or missing citation → do not claim confidence", "https://github.com/NIGHTPURI/incident-lens/blob/main/docs/AI_ENGINEERING.md"),
];
